const { sequelize } = require('./config/db');
const RecruitmentNoticeInfo = require('./models/ITInfo/RecruitmentNoticeInfo/recruitmentNoticeInfoModel');

const recruitmentNotices = [
{
  "title": "웹 S/W 개발자 경력직 채용",
  "startdate": "2024-07-23T11:00:00.000Z",
  "enddate": "2024-08-05T23:59:59.000Z",
  "resultdate": "2024-08-29T00:00:00.000Z",
  "pic1": "",
  "pic2": "",
  "pic3": "",
  "pic4": "",
  "pic5": "",
  "body": "어빌리티시스템즈는 2004년 설립 이래 도전정신과 신뢰를 바탕으로 끊임없이 성장해온 기업입니다. 현재 폭넓은 네트워크 서비스와 시스템 구축으로 다양한 레퍼런스를 보유하고 있습니다. 함께 성장할 인재분들의 많은 지원 바랍니다.",
  "experience": "경력 3~13년",
  "education": "학력무관",
  "stack": "JAVA, JavaScript, jQuery, Spring, Oracle, MYSQL, PostgreSQL",
  "qualification": "웹개발 관련 경험자, DBMS 사용 경험자, 원활한 의사소통을 가지고 논리적으로 팀원들과 함께 문제해결이 가능한 분",
  "preferences": "전자정부프레임워크 및 공공기관 프로젝트 경험이 있는분, 버전관리(SVN/Git), 빌드툴(Maven), JAVA IDE(Eclipse, STS, Intelij) 경험이 있는 분, HTML5, Angular, React, vue.js등 최신 스펙에 대한 이해가 있는 분, 웹 시스템 최적화 및 성능개선 경험이 있는 분, Linux, WAS/WEB 설치 및 운영 가능자, 비즈니스 로직을 논리적으로 분석, 설계, 구현이 가능한 분",
  "work_type": "정규직 수습기간 3개월",
  "salary": "협의 후 결정",
  "location": "세종특별자치시",
  "work_time": "주 5일(월~금) 오전9시 30분 ~ 오후 6시",
  "recruit_part": "개발, 디자인, 마케팅",
  "duties": "공공기관 웹 시스템 개발 및 유지보수, 자사 솔루션 개발 및 운영, 프로젝트 업무 분석 및 설계",
  "key_skills": "원활한 의사소통, 논리적인 사고",
  "recruit_num": 1,
  "link": "https://www.saramin.co.kr/zf_user/jobs/relay/view?isMypage=no&rec_idx=48666650&recommend_ids=eJxFzrENA1EIA9Bp0hswGOoMkv23SHLH10k0T8YCAhphPnjpTXTyNzfcmDTdMILK3rWErOt0FA5shxWqWAxJ9ZNE8IGfox7wsoNqcbYTMdbapIPXo212MZ1h%2BPMLSBcqbA%3D%3D&view_type=list&gz=1&t_ref_content=general&t_ref=area_recruit&relayNonce=fd32bb17eca0b36ba73a&immediately_apply_layer_open=n#seq=0",
  "companyname": "(주)어빌리티시스템즈"
},
{
  "title": "대전/세종/전주/부산/광주 지방 웹개발 경력자 찾습니다.",
  "startdate": "2024-07-11T16:00:00.000Z",
  "enddate": "2024-08-10T23:59:59.000Z",
  "resultdate": null,
  "pic1": "",
  "pic2": "",
  "pic3": "",
  "pic4": "",
  "pic5": "",
  "body": "체스트넛은 Web/Apps 개발 사업 및 자문, SI/SM Team Project Outsourcing을 하는 IT기업입니다. 다양한 비즈니스 영역에 플랫폼을 개발하고 세상을 편리하고 스마트하게 만드는데 일조하고자 합니다.",
  "experience": "경력 4년 ~ 20년",
  "education": "학력무관",
  "stack": "JAVA, JSP, SQL, React, Vue",
  "qualification": "웹개발 관련 경력 4년 ~ 20년, JAVA, JSP, SQL, Front-end / Back-end 개발 가능자, React, Vue, 풀스택 개발 가능자 우대",
  "preferences": "",
  "work_type": "프리랜서, 정규직 or 계약직(무기계약직)",
  "salary": "협의 후 결정",
  "location": "세종특별자치시",
  "work_time": "",
  "recruit_part": "",
  "duties": "",
  "key_skills": "",
  "recruit_num": 0,
  "link": "https://www.saramin.co.kr/zf_user/jobs/relay/view?isMypage=no&rec_idx=48592985&recommend_ids=eJxFzsENxEAIA8Bq7m%2FAYPadQtJ%2FF7fKcjmJzwhjQUBLWDc%2BuoiErGvQyT0HbkyaBoukehDwsl9BKxw4iAiDDZxFlL3Ysbkxgsr%2Bb1Rx0MHntzZ7mM7d%2BLI6xN7UF5EWKr0%3D&view_type=search&searchType=search&gz=1&t_ref_content=generic&t_ref=search&relayNonce=ca99eec0caa659eba95d&paid_fl=n&search_uuid=74163f0a-0367-4d28-b334-656886f2f5d2&immediately_apply_layer_open=n#seq=0",
  "companyname": "(주)체스트넛"
},
{
  "title": "방화벽 및 네트워크 엔지니어 채용",
  "startdate": "2024-06-19T16:00:00.000Z",
  "enddate": "2024-08-18T23:59:59.000Z",
  "resultdate": null,
  "pic1": "",
  "pic2": "",
  "pic3": "",
  "pic4": "",
  "pic5": "",
  "body": "우리 회사는 IT 분야의 여러 영역에서 전문적인 서비스를 제공하고 있습니다. 고객의 비즈니스에 필요한 모든 IT 솔루션을 한 곳에서 제공하며, 고객이 성공적인 비즈니스를 운영할 수 있도록 지원하고 있습니다.",
  "experience": "경력 3년 이상",
  "education": "학력무관",
  "stack": "방화벽 관리",
  "qualification": "네트워크 보안 및 방화벽 관리 경험, CCNA, 네트워크 장비 및 보안 솔루션에 대한 전문 지식 보유, 문제 해결 및 분석 능력이 뛰어나고 적응력이 있는 분",
  "preferences": "CCNP 등과 같은 인증 자격증 소지자 우대",
  "work_type": "정규직",
  "salary": "연봉 4,000만원(주 40시간)",
  "location": "세종특별자치시",
  "work_time": "주 5일 근무, 유연한 근무 시간 제도 운영",
  "recruit_part": "방화벽 및 네트워크 엔지니어",
  "duties": "[방화벽 엔지니어] 방화벽 관리 및 유지보수 업무, 방화벽, IPS 등 네트워크 보안 제품군 신규 설치 및 구축\n[네트워크 엔지니어] 네트워크 장비의 관리 및 유지보수 업무, L2, L3 스위치 및 AP 등 신규 설치 및 구축",
  "key_skills": "",
  "recruit_num": 2,
  "link": "https://www.saramin.co.kr/zf_user/jobs/relay/view?isMypage=no&rec_idx=48440047&recommend_ids=eJxNj8ERA1EIQqvJXQVRzykk%2FXeR3c3MNzffgIhsOaT8tNur3uyMCb9RDyKUqFUhr1XTjNEX%2Bs9czpo1i95Ys0yGo8rC%2FpIxzfQTxWuwWhz0bMmrxAyOKpZj7wJB2MGYJLm7Qc0i8y62aCrGvu9RfO5%2BAWKhQEI%3D&view_type=search&searchType=search&gz=1&t_ref_content=generic&t_ref=search&relayNonce=2b13c0a52821f961fd90&paid_fl=n&search_uuid=9b4350a9-fa10-426a-bcee-98a005772a12&immediately_apply_layer_open=n#seq=0",
  "companyname": "(주)에스씨정보"
},
{
  "title": "SI 프로젝트 수행 개발자 채용",
  "startdate": "2024-06-19T16:00:00.000Z",
  "enddate": "2024-08-18T23:59:59.000Z",
  "resultdate": null,
  "pic1": "",
  "pic2": "",
  "pic3": "",
  "pic4": "",
  "pic5": "",
  "body": "우리 회사는 IT 분야의 여러 영역에서 전문적인 서비스를 제공하고 있습니다. 고객의 비즈니스에 필요한 모든 IT 솔루션을 한 곳에서 제공하며, 고객이 성공적인 비즈니스를 운영할 수 있도록 지원하고 있습니다.",
  "experience": "신입 ~ 2년차",
  "education": "4년제 대졸 학사 이상, 컴퓨터공학, 소프트웨어 공학 등 IT 및 개발 관련 전공자",
  "stack": "JAVA, C#, JavaScript, Spring, MS-SQL, Oracle, MariaDB, Linux",
  "qualification": "네트워크 보안 및 방화벽 관리 경험, CCNA, 네트워크 장비 및 보안 솔루션에 대한 전문 지식 보유, 문제 해결 및 분석 능력이 뛰어나고 적응력이 있는 분",
  "preferences": "운전면허, 포트폴리오, 정보처리기사 및 SQLD, 넥사크로 경험자, 웹서비스 개발 및 운영 경험자, HTML, CSS 경험자(소스 분석 및 수정이 가능한 수준), Spring 환경셋팅 경험자, 청주/세종/대전 거주자",
  "work_type": "정규직",
  "salary": "평균 연봉 5,912만원",
  "location": "세종특별자치시",
  "work_time": "주 5일 근무, 09:00~18:00",
  "recruit_part": "SI 프로젝트 수행 개발자",
  "duties": "SI 프로젝트 수행, Java(C#) 및 JavaScript, Spring 프레임워크를 이용한 개발 업무, MS-SQL, Oracle, MariaDB 등 데이터베이스 관리, Linux 환경에서의 개발 및 운영",
  "key_skills": "JAVA, C#, JavaScript, Spring, MS-SQL, Oracle, MariaDB, Linux",
  "recruit_num": 2,
  "link": "https://www.saramin.co.kr/zf_user/jobs/relay/view?isMypage=no&rec_idx=48637733&recommend_ids=eJxNjsERAzEIA6vJHxAI%2BZ1Crv8u4jgzJs8dSSwpBAv9yPnqd6ptlfuzLA4yGoyd%2BsGKZMUtV5qt2SYbnbdMCY4pe%2FmyjfZDNLOuqLItcFOkgpqUZT5eAhJvOfcb2fNk0ZcGZVs8W%2BHrHQzYeNts7%2F8uL%2BcRfQB0iUBk&view_type=search&searchType=search&gz=1&t_ref_content=generic&t_ref=search&relayNonce=0ff9ca14b7c64c1e84d0&paid_fl=n&search_uuid=9b4350a9-fa10-426a-bcee-98a005772a12&immediately_apply_layer_open=n#seq=0",
  "companyname": "(주)지비티"
},
{
  "title": "비전세미콘(주) 기술연구소 SW 개발 경력자 모집",
  "startdate": "2024-07-30T16:00:00.000Z",
  "enddate": "2024-09-28T23:59:59.000Z",
  "resultdate": null,
  "pic1": "",
  "pic2": "",
  "pic3": "",
  "pic4": "",
  "pic5": "",
  "body": "비전세미콘(주)은 IT 분야의 여러 영역에서 전문적인 서비스를 제공하고 있습니다. 고객의 비즈니스에 필요한 모든 IT 솔루션을 한 곳에서 제공하며, 고객이 성공적인 비즈니스를 운영할 수 있도록 지원하고 있습니다.",
  "experience": "경력 3년 ↑",
  "education": "대졸(2,3년제) 이상(예정자 가능)",
  "stack": "JAVA, C#, JavaScript, Spring, MS-SQL, Oracle, MariaDB, Linux",
  "qualification": "FrontEnd, BackEnd 개발 경력자, C#/자바스크립트/MS-SQL사용 가능자",
  "preferences": "키오스크 등 결제 시스템 개발 경험자, Android App, iOS App개발 경험자",
  "work_type": "정규직",
  "salary": "협의 후 결정",
  "location": "세종특별자치시",
  "work_time": "주 5일(월~금) 08:30~17:30",
  "recruit_part": "기술연구소 SW 개발",
  "duties": "",
  "key_skills": "",
  "recruit_num": 0,
  "link": "https://www.saramin.co.kr/zf_user/jobs/relay/view?isMypage=no&rec_idx=48708369&recommend_ids=eJxNkDESxDAIA19zPRgh4ToPyf9%2FcSSFScfOMhI2ipDHvsvtpwtFWxZq9BdTBmGQRotGvhhyaB%2FLBW6cKJlV5rGycNUsuwenN2IhbGw6aKeIKWpsrqDy2NyRn6islRiLfM6eqK7l2J7JeQJ6MH1%2BQ5332D9nWEBn&view_type=search&searchType=search&gz=1&t_ref_content=generic&t_ref=search&relayNonce=f72f62e26afd031d9363&paid_fl=n&search_uuid=00897db8-8cd8-4072-bdfe-1ad2b7ab103c&immediately_apply_layer_open=n#seq=0",
  "companyname": "비전세미콘(주)"
},
{
  "title": "대전,세종 로버트보쉬코리아 PC유지보수 OA기기 유지보수",
  "startdate": "2024-07-10T10:00:00.000Z",
  "enddate": "2024-08-09T23:59:00.000Z",
  "resultdate": null,
  "pic1": "",
  "pic2": "",
  "pic3": "",
  "pic4": "",
  "pic5": "",
  "body": "에스휴먼(주)은 IT 분야의 여러 영역에서 전문적인 서비스를 제공하고 있습니다. 고객의 비즈니스에 필요한 모든 IT 솔루션을 한 곳에서 제공하며, 고객이 성공적인 비즈니스를 운영할 수 있도록 지원하고 있습니다.",
  "experience": "신입·경력 1년 ↑",
  "education": "학력무관(예정자 가능)",
  "stack": "PC관리",
  "qualification": "학력 및 전공",
  "preferences": "관련경력 및 자격증소지자 우대",
  "work_type": "계약직, 파견직",
  "salary": "협의 후 결정",
  "location": "세종특별자치시, 대전전체",
  "work_time": "주 5일(월~금)",
  "recruit_part": "PC, OA기기 / 유지보수",
  "duties": "",
  "key_skills": "PC관리, IT장비 관리 및 설치",
  "recruit_num": 0,
  "link": "https://www.saramin.co.kr/zf_user/jobs/relay/view?isMypage=no&rec_idx=48580709&recommend_ids=eJxNzssNQ0EIQ9FqsrfBA2adQtJ%2FF3l6M%2Fksj9CVEdDTmBce%2FRRWkcyNGEntjcwkiIOyzdpQdFmnUeUgPxelIvADHBtLXYjTrDWgzo5T9zsmb67QNfzPmPqynH2VZr8B68srPw%3D%3D&view_type=search&searchType=search&gz=1&t_ref_content=generic&t_ref=search&relayNonce=3266758c0f2aafcb735b&paid_fl=n&search_uuid=55f3c0f8-f658-4603-85e8-275f9631f663&immediately_apply_layer_open=n#seq=0",
  "companyname": "에스휴먼(주)"
},
{
  "title": "시스템 운영(SM)관리 상주 엔지니어 모집(세종)",
  "startdate": "2024-07-29T16:00:00.000Z",
  "enddate": "2024-08-28T23:59:00.000Z",
  "resultdate": null,
  "pic1": "",
  "pic2": "",
  "pic3": "",
  "pic4": "",
  "pic5": "",
  "body": "대신네트웍스(주)은 IT 분야의 여러 영역에서 전문적인 서비스를 제공하고 있습니다. 고객의 비즈니스에 필요한 모든 IT 솔루션을 한 곳에서 제공하며, 고객이 성공적인 비즈니스를 운영할 수 있도록 지원하고 있습니다.",
  "experience": "경력 7년 ↑",
  "education": "대졸(2,3년제) 이상",
  "stack": "Spring, Linux",
  "qualification": "자격증: 정보처리기사, 정보처리산업기사, 리눅스마스터2급",
  "preferences": "해당직무 인턴경력, 해당직무 근무경험, Spring 개발 경험",
  "work_type": "정규직, 계약직",
  "salary": "협의 후 결정",
  "location": "세종특별자치시",
  "work_time": "주 5일(월~금) 09:00~18:00",
  "recruit_part": "서버관리 및 운영, 시스템 성능 분석, 보안 정책 수립",
  "duties": "경력(과장, 차장, 부장급)",
  "key_skills": "",
  "recruit_num": 0,
  "link": "https://www.saramin.co.kr/zf_user/jobs/relay/view?isMypage=no&rec_idx=48705533&recommend_ids=eJxFzbERxEAIA8BqPhegAxG7EPffxTNzPjtcpBEkg5Df%2BNVFJkKojSpiOTfmmp564IumOsgKxIOAGn3g3pkH1qH8EsUHW29tPobhltnO2DV7h5PO5MtUFDWsPwGYK3I%3D&view_type=search&searchType=search&gz=1&t_ref_content=generic&t_ref=search&relayNonce=36b968eb41ca3449324c&paid_fl=n&search_uuid=55f3c0f8-f658-4603-85e8-275f9631f663&immediately_apply_layer_open=n#seq=0",
  "companyname": "대신네트웍스(주)"
},
{
  "title": "[하랑에듀] LMS관리 부문 신입/경력 채용",
  "startdate": "2024-07-26T10:00:00.000Z",
  "enddate": "2024-08-11T18:00:00.000Z",
  "resultdate": null,
  "pic1": "",
  "pic2": "",
  "pic3": "",
  "pic4": "",
  "pic5": "",
  "body": "(주)하랑에듀는 교육 분야에서 LMS(Learning Management System) 관리를 전문적으로 제공하는 기업입니다. 고객의 학습 관리 및 교육 솔루션을 통해 효과적인 학습 환경을 제공합니다.",
  "experience": "무관(신입포함)",
  "education": "대졸(2,3년제) 이상",
  "stack": "PHP, JavaScript, MYSQL, jQuery, Ajax",
  "qualification": "경력 1년이상",
  "preferences": "해당직무 근무경험, 사업주 훈련과정 LMS 시스템 유지보수 경험자",
  "work_type": "정규직",
  "salary": "협의 후 결정",
  "location": "세종특별자치시",
  "work_time": "주 5일(월~금) 09:00~18:00",
  "recruit_part": "LMS 유지보수 및 신규 기능 개발, 리뉴얼 개발, 리눅스 서버관리",
  "duties": "사원",
  "key_skills": "LMS",
  "recruit_num": 0,
  "link": "https://www.saramin.co.kr/zf_user/jobs/relay/view?isMypage=no&rec_idx=48689512&recommend_ids=eJxNzssNw0AIhOFqfJ%2BBWR7nFJL%2Bu%2FBqTawcPwG%2FEJCd6C%2Bu%2FAgLyYoHRi0xBy0pa%2BCw4Ny4O0HMRCEEX7j90haV6gm4wN0eLO%2BIWSvXeafIw2Xa%2BX9ax8soT9Vm3unWK0A%3D&view_type=search&searchType=search&gz=1&t_ref_content=generic&t_ref=search&relayNonce=d7cf35a443ce9ff6ffa3&paid_fl=n&search_uuid=55f3c0f8-f658-4603-85e8-275f9631f663&immediately_apply_layer_open=n#seq=0",
  "companyname": "(주)하랑에듀"
},
{
  "title": "경영본부 IT 전산팀[개발자]",
  "startdate": "2024-07-26T09:00:00.000Z",
  "enddate": null,
  "resultdate": null,
  "pic1": "",
  "pic2": "",
  "pic3": "",
  "pic4": "",
  "pic5": "",
  "body": "(주)엠케이코리아는 다양한 산업 분야에서 IT 솔루션과 서비스를 제공하는 기업입니다. 경영본부 IT 전산팀에서는 내부 시스템 관리 및 개발을 담당할 인재를 찾고 있습니다.",
  "experience": "신입",
  "education": "학력무관(예정자 가능)",
  "stack": "C#, DevExpress, MS-SQL",
  "qualification": "무관",
  "preferences": "",
  "work_type": "정규직",
  "salary": "협의 후 결정",
  "location": "세종특별자치시",
  "work_time": "주 5일(월~금)",
  "recruit_part": "ERP개발, MES유지보수",
  "duties": "",
  "key_skills": "",
  "recruit_num": 0,
  "link": "https://www.saramin.co.kr/zf_user/jobs/relay/view?isMypage=no&rec_idx=48689403&recommend_ids=eJxVkEsOAzEIQ0%2FTvQkYM%2BsepPe%2FRTMZCdpdnvyJRVRiwfUps5feUVnl5hvxYMj8auTlzKvNXJ7iqMbU2pgH76TFmBMJbzUFKhppQFhXuSw0HyW0bFSuvyoK8VOV1C7vrIDijNxoZ%2FNjDt7DZjPcVJ2N%2FcA5zhdhnEA%2B&view_type=search&searchType=search&gz=1&t_ref_content=generic&t_ref=search&relayNonce=f53a0b96b66e8246e086&paid_fl=n&search_uuid=55f3c0f8-f658-4603-85e8-275f9631f663&immediately_apply_layer_open=n#seq=0",
  "companyname": "(주)엠케이코리아"
},
{
  "title": "JAVA 웹 개발자 채용(신입/경력)",
  "startdate": "2024-07-26T08:00:00.000Z",
  "enddate": "2024-08-25T23:59:00.000Z",
  "resultdate": null,
  "pic1": "",
  "pic2": "",
  "pic3": "",
  "pic4": "",
  "pic5": "",
  "body": "(주)공감아이티는 다양한 산업 분야에서 IT 솔루션과 서비스를 제공하는 기업입니다. JAVA 웹 개발자를 채용하여 신입 및 경력자 모두 지원 가능합니다.",
  "experience": "신입·경력(년수무관)",
  "education": "대졸(2,3년제) 이상(예정자 가능)",
  "stack": "JAVA, Spring, MYSQL, JavaScript",
  "qualification": "정보처리기사, 1종보통운전면허, 2종보통운전면허(오토)",
  "preferences": "공학계열 전공자, 운전가능자, 구성원과 원활한 커뮤니케이션 능력",
  "work_type": "정규직",
  "salary": "협의 후 결정",
  "location": "세종특별자치시, 대전 유성구",
  "work_time": "주 5일(월~금) 09:00~18:00",
  "recruit_part": "웹 개발, 시스템 유지보수",
  "duties": "",
  "key_skills": "",
  "recruit_num": 0,
  "link": "https://www.saramin.co.kr/zf_user/jobs/relay/view?isMypage=no&rec_idx=48688313&recommend_ids=eJxNj8ENQzEIQ6fpHcdg4NxBuv8WbfSrkOOT0bPxSrOK%2BBT0yreXKK%2BNeNCWMQ%2F%2BjpE7tT8SWXMMUH3SINmD5HLaQSG7OWaw4VcR3e0yU5qR0d3lUySTjUq%2BZZM24161qLxUCOWa99MiZ0bAzLHTL2FYQFA%3D&view_type=search&searchType=search&gz=1&t_ref_content=generic&t_ref=search&relayNonce=2d118acfd5dd7a7ebbe5&paid_fl=n&search_uuid=55f3c0f8-f658-4603-85e8-275f9631f663&immediately_apply_layer_open=n#seq=0",
  "companyname": "(주)공감아이티"
},
{
  "title": "2024년 3분기 각 부문 신입/경력 직원 채용",
  "startdate": "2024-06-05T00:00:00.000Z",
  "enddate": null,
  "resultdate": null,
  "pic1": "https://www.xcs.co.kr/static/recruit/saramin/image/room1.jpg",
  "pic2": "https://www.xcs.co.kr/static/recruit/saramin/image/room5.jpg",
  "pic3": "https://www.xcs.co.kr/static/recruit/saramin/image/room3.jpg",
  "pic4": "https://www.xcs.co.kr/static/recruit/saramin/image/room4.jpg",
  "pic5": "",
  "body": "(주)엑스코어시스템은 다양한 산업 분야에서 IT 솔루션과 서비스를 제공하는 기업입니다. 각 부문에서 신입 및 경력 직원을 채용하며, 면접비 지원 등의 혜택을 제공합니다.",
  "experience": "신입·경력 1년 이상",
  "education": "학력무관",
  "stack": "JAVA, Spring, MYSQL, JavaScript",
  "qualification": "JAVA 1~10년이상",
  "preferences": "컴퓨터 공학 등 관련 전공자, 정보처리기사, 모바일 앱 개발 경험, REST API 연동 경험자",
  "work_type": "정규직",
  "salary": "협의 후 결정 (학사 초임기준 270만원)",
  "location": "세종특별자치시",
  "work_time": "주 5일(월~금) 10:00~18:00",
  "recruit_part": "웹 개발, 시스템 유지보수",
  "duties": "능동적인 커뮤니케이션 역량",
  "key_skills": "공공 SI PJT 개발 투입 경험, PPT디자인 업무경험",
  "recruit_num": 0,
  "link": "https://www.saramin.co.kr/zf_user/jobs/relay/view?isMypage=no&rec_idx=48326537&recommend_ids=eJxVj8sRw0AMQqvJXRLod3Yh7r%2BLrJ2Z1eb4BhCI5SK0ukv1kxcrBaQsjBdDEeFbdYTmg%2FLDkBAMlnnJNi9r96hBj4w%2FM30XpUj5XEYqs6e34XHgyvpkASPkMHcXj81ATxZVTDv%2FNdMZ2W6do6oZH1W%2FbNxAZA%3D%3D&view_type=search&searchType=search&gz=1&t_ref_content=generic&t_ref=search&relayNonce=bd43e10267dee8a04f19&paid_fl=n&search_uuid=55f3c0f8-f658-4603-85e8-275f9631f663&immediately_apply_layer_open=n#seq=0",
  "companyname": "(주)엑스코어시스템"
},
{
  "title": "[경력] 응용SW개발자(JAVA,JSP, SQL) 채용 공고",
  "startdate": "2024-08-17T09:00:00.000Z",
  "enddate": "2024-09-15T23:59:00.000Z",
  "resultdate": null,
  "pic1": "",
  "pic2": "",
  "pic3": "",
  "pic4": "",
  "pic5": "",
  "body": "지엔소프트(주)는 다양한 산업 분야에서 IT 솔루션과 서비스를 제공하는 기업입니다. 응용 소프트웨어 개발자를 채용하며, 면접비 지원 등의 혜택을 제공합니다.",
  "experience": "경력 3년 이상",
  "education": "학력무관",
  "stack": "JAVA, JSP, SQL",
  "qualification": "해당직무 근무경험",
  "preferences": "컴퓨터 공학 등 관련 전공자, 정보처리기사",
  "work_type": "정규직, 프리랜서",
  "salary": "협의 후 결정",
  "location": "세종특별자치시, 대전 유성구",
  "work_time": "주 5일(월~금) 09:00~18:00",
  "recruit_part": "응용 소프트웨어 개발",
  "duties": "무관",
  "key_skills": "공공기관 SI 사업 경력자",
  "recruit_num": 0,
  "link": "https://www.saramin.co.kr/zf_user/jobs/relay/view?isMypage=no&rec_idx=48627362&recommend_ids=eJxVj8EVA0EIQqvJnRFFPaeQ9N9FZjfvjZvjF0T00qIUn1p65dsrgYoL141hbWtQCPMe7K3nmMvCH7uAWx0kzYmN%2BKkke6KiGepTg1WedswJuuOo0d3lf3drVK3s5pgFgSeKuTx7auzdmPdF7dnzQd3J%2BAJ%2BJECL&view_type=search&searchType=search&gz=1&t_ref_content=generic&t_ref=search&relayNonce=0fbf979c9ca9e5e0b180&paid_fl=n&search_uuid=55f3c0f8-f658-4603-85e8-275f9631f663&immediately_apply_layer_open=n#seq=0",
  "companyname": "지엔소프트(주)"
},
{
  "title": "[AI인공지능/정보보안] 솔루션 기술지원 엔지니어 (세종, 서울)",
  "startdate": "2024-07-24T09:00:00.000Z",
  "enddate": "2024-08-06T23:59:00.000Z",
  "resultdate": null,
  "pic1": "",
  "pic2": "",
  "pic3": "",
  "pic4": "",
  "pic5": "",
  "body": "(주)컴트루테크놀로지는 다양한 산업 분야에서 IT 솔루션과 서비스를 제공하는 기업입니다. AI인공지능 및 정보보안 솔루션 기술지원 엔지니어를 채용하며, 면접비 지원 등의 혜택을 제공합니다.",
  "experience": "무관(신입포함)",
  "education": "학력무관",
  "stack": "Linux, Ubuntu, RedHat",
  "qualification": "해당직무 근무경험",
  "preferences": "컴퓨터 공학 등 관련 전공자, 네트워크 보안 제품 경력자",
  "work_type": "정규직, 프리랜서",
  "salary": "협의 후 결정",
  "location": "세종특별자치시, 서울특별시",
  "work_time": "주 5일(월~금) 09:00~18:00",
  "recruit_part": "AI인공지능/정보보안 솔루션 기술지원",
  "duties": "병역특례 : 보충역만 가능(이직자 제외)",
  "key_skills": "운전 가능자(필수)",
  "recruit_num": 0,
  "link": "https://www.saramin.co.kr/zf_user/jobs/relay/view?isMypage=no&rec_idx=48673016&recommend_ids=eJxVj8EVA0EIQqvJnRFFPaeQ9N9FZjfvjZvjF0T00qIUn1p65dsrgYoL141hbWtQCPMe7K3nmMvCH7uAWx0kzYmN%2BKkke6KiGepTg1WedswJuuOo0d3lf3drVK3s5pgFgSeKuTx7auzdmPdF7dnzQd3J%2BAJ%2BJECL&view_type=search&searchType=search&gz=1&t_ref_content=generic&t_ref=search&relayNonce=0fbf979c9ca9e5e0b180&paid_fl=n&search_uuid=55f3c0f8-f658-4603-85e8-275f9631f663&immediately_apply_layer_open=n#seq=0",
  "companyname": "(주)컴트루테크놀로지"
},
{
  "title": "[보안운영] 정보보안 유지관리 엔지니어 채용",
  "startdate": "2024-07-20T20:00:00.000Z",
  "enddate": "2024-08-19T23:59:00.000Z",
  "resultdate": null,
  "pic1": "",
  "pic2": "",
  "pic3": "",
  "pic4": "",
  "pic5": "",
  "body": "주식회사케이소프트는 정보보안 솔루션을 제공하는 기업으로, 정보보안 유지관리 엔지니어를 채용합니다. 다양한 혜택과 함께 경력 무관하게 지원 가능합니다.",
  "experience": "무관(신입포함)",
  "education": "대졸(2,3년제) 이상",
  "stack": "정보보호",
  "qualification": "정보보안 관련 학위 또는 자격증 소지자",
  "preferences": "정보보안 관련 직무 경험자",
  "work_type": "정규직",
  "salary": "협의 후 결정",
  "location": "세종특별자치시",
  "work_time": "주 5일(월~금) 09:00~18:00",
  "recruit_part": "정보보안 유지관리",
  "duties": "정보보안 시스템 유지 및 관리, 보안 정책 수립 및 시행",
  "key_skills": "정보보안 관련 자격증 소지자 우대",
  "recruit_num": 1,
  "link": "https://www.saramin.co.kr/zf_user/jobs/relay/view?isMypage=no&rec_idx=48651460&recommend_ids=eJxNjrkRw0AMA6txThLgc7EKUf9d%2BHT2kAp3FsCAFUzFukvjkxcrxAS5UQ8%2BTrlRDiKVudqGKuLVNcZiW8AI6W54RkqHfcFP92ddhFaDANYsuyHSx6Yw51XsF%2BHzWaT8jdCsntpWz9T%2F825SZ7nMS7r7IM%2FUF3DeQF4%3D&view_type=search&searchType=search&gz=1&t_ref_content=generic&t_ref=search&relayNonce=819e2cfc9cc8b44ec4ba&paid_fl=n&search_uuid=d94edd89-3b03-421a-bb56-a8cbcd178094&immediately_apply_layer_open=n#seq=0",
  "companyname": "주식회사케이소프트"
},
{
  "title": "[상상스토리/세종] 웹 개발 및 유지보수 경력개발자 채용공고",
  "startdate": "2024-07-10T10:00:00.000Z",
  "enddate": "2024-08-09T23:59:00.000Z",
  "resultdate": null,
  "pic1": "",
  "pic2": "",
  "pic3": "",
  "pic4": "",
  "pic5": "",
  "body": "상상스토리(주)는 웹 개발 및 유지보수를 담당할 경력개발자를 채용합니다. 다양한 혜택과 함께 경력자들의 많은 지원 바랍니다.",
  "experience": "경력 5~7년",
  "education": "대졸(2,3년제) 이상",
  "stack": "JAVA, JSP",
  "qualification": "초대졸, 경력 5~6년차",
  "preferences": "정보처리기사, 인근거주자, 해당직무 근무경험",
  "work_type": "정규직, 프리랜서",
  "salary": "협의 후 결정",
  "location": "세종특별자치시",
  "work_time": "주 5일(월~금) 09:00~18:00",
  "recruit_part": "웹 개발 및 유지보수",
  "duties": "웹 개발 및 유지보수 업무 담당",
  "key_skills": "",
  "recruit_num": 1,
  "link": "https://www.saramin.co.kr/zf_user/jobs/relay/view?isMypage=no&rec_idx=48580519&recommend_ids=eJxNkMERAzEIA6vJHxBI5p1C0n8XOSczxs9FCwPkYsrRn%2BX%2B0jsXLQwadJB1cKueD9oPIU%2F1QfpjXxjJ3jL%2FMiJhk5YoO2k16uots4w1KYCeJStA1YwCn9pJ0SvLZ5QsNWtUGA2DXlRcJygwMkPh%2Bxv2BWvOQFg%3D&view_type=search&searchType=search&gz=1&t_ref_content=generic&t_ref=search&relayNonce=ed771e81218f6d05a6d2&paid_fl=n&search_uuid=d94edd89-3b03-421a-bb56-a8cbcd178094&immediately_apply_layer_open=n#seq=0",
  "companyname": "상상스토리(주)"
},
{
  "title": "VMware 구축, 유지보수 엔지니어 신입 및 경력 모집",
  "startdate": "2024-07-08T12:00:00.000Z",
  "enddate": "2024-08-07T23:59:00.000Z",
  "resultdate": null,
  "pic1": "",
  "pic2": "",
  "pic3": "",
  "pic4": "",
  "pic5": "",
  "body": "아이리스인포테크주식회사는 VMware 구축 및 유지보수를 담당할 신입 및 경력 엔지니어를 모집합니다. 다양한 혜택과 함께 지원 가능합니다.",
  "experience": "무관(신입포함)",
  "education": "학력무관",
  "stack": "VMware, vSAN",
  "qualification": "컴퓨터/시스템공학 전공자 우대",
  "preferences": "VMware자격증 소지자, HCI 구축 경험 보유자",
  "work_type": "정규직",
  "salary": "협의 후 결정",
  "location": "세종특별자치시, 대전전체",
  "work_time": "주 5일(월~금)",
  "recruit_part": "VMware 구축 및 유지보수",
  "duties": "VMware 시스템 구축 및 유지보수, 관련 기술 지원",
  "key_skills": "P2V 마이그레이션 수행능력",
  "recruit_num": 1,
  "link": "https://www.saramin.co.kr/zf_user/jobs/relay/view?isMypage=no&rec_idx=48564183&recommend_ids=eJxNj8sRQzEIA6vJHSwh4XMKSf9d5H1mbB8XDWJhK0bAv878%2BMuGk54LRSdu1IPloHlhvGlZjoWUcaYJqfbuROmoiuDohawuxUIH0n1UXV3bquQ%2BJaFrtnFQkwvvB3JbAYPYzgWlt6RzDOaRAvM59AeDUkBx&view_type=search&searchType=search&gz=1&t_ref_content=generic&t_ref=search&relayNonce=15c53f6bc93bd153cc19&paid_fl=n&search_uuid=d94edd89-3b03-421a-bb56-a8cbcd178094&immediately_apply_layer_open=n#seq=0",
  "companyname": "아이리스인포테크주식회사"
},
{
  "title": "사업관리부 정보통신유지보수 업무 정규직 채용",
  "startdate": "2024-07-08T09:00:00.000Z",
  "enddate": "2024-08-07T23:59:00.000Z",
  "resultdate": null,
  "pic1": "",
  "pic2": "",
  "pic3": "",
  "pic4": "",
  "pic5": "",
  "body": "(주)씨앤은 정보통신유지보수 업무를 담당할 신입 및 경력 직원을 모집합니다. 다양한 혜택과 함께 지원 가능합니다.",
  "experience": "신입·경력 1~10년",
  "education": "학력무관",
  "stack": "네트워크, 정보통신",
  "qualification": "운전가능자",
  "preferences": "",
  "work_type": "정규직",
  "salary": "연봉 3,200 만원 (주 40시간)",
  "location": "세종특별자치시",
  "work_time": "주 5일(월~금) 09:00~18:00",
  "recruit_part": "정보통신유지보수",
  "duties": "정보통신 시스템 유지 및 관리, 네트워크 구축 및 기술 지원",
  "key_skills": "운전",
  "recruit_num": 1,
  "link": "https://www.saramin.co.kr/zf_user/jobs/relay/view?isMypage=no&rec_idx=48560325&recommend_ids=eJxNj0EWAzEIQk%2FTPUaEzLoH6f1v0TSdF2f5FQE5hYH0ZwZefnOmg74WaqPoyMYyaB6xyjJaHClVi68s%2FW5jo4Fwb1mzhMc2w%2FOgYnl1LtccXXKl6OFMyBxttRpHl8wcTBys1L8GbvEYjA6Scz941xjUta2%2BfS9AXw%3D%3D&view_type=search&searchType=search&gz=1&t_ref_content=generic&t_ref=search&relayNonce=6afc800ebf0ddc2cce4b&paid_fl=n&search_uuid=d94edd89-3b03-421a-bb56-a8cbcd178094&immediately_apply_layer_open=n#seq=0",
  "companyname": "(주)씨앤"
},
{
  "title": "[경력]세종시 Linux&웹/모바일앱 개발 및 운영(세종시 근무)",
  "startdate": "2024-07-04T09:00:00.000Z",
  "enddate": null,
  "resultdate": null,
  "pic1": "",
  "pic2": "",
  "pic3": "",
  "pic4": "",
  "pic5": "",
  "body": "(주)디더블유아이는 세종시에서 Linux 및 웹/모바일 앱 개발 및 운영을 담당할 경력직 직원을 모집합니다. 다양한 혜택과 함께 지원 가능합니다.",
  "experience": "경력 1~10년",
  "education": "초대졸 이상",
  "stack": "JAVA, Linux, CUBRID",
  "qualification": "인근거주자, 해당직무 근무경험",
  "preferences": "",
  "work_type": "정규직, 계약직, 파견직",
  "salary": "연봉 3,600 만원 (주 40시간)",
  "location": "세종특별자치시",
  "work_time": "주 5일(월~금) 09:00~18:00",
  "recruit_part": "Linux&웹/모바일앱 개발 및 운영",
  "duties": "Linux 시스템 및 웹/모바일 앱 개발 및 운영, 관련 기술 지원",
  "key_skills": "연구원, 팀원급 경력",
  "recruit_num": 1,
  "link": "https://www.saramin.co.kr/zf_user/jobs/relay/view?isMypage=no&rec_idx=48540097&recommend_ids=eJxNj8sRQzEIA6vJHSwh4XMKSf9d5H1mbB8XDWJhK0bAv878%2BMuGk54LRSdu1IPloHlhvGlZjoWUcaYJqfbuROmoiuDohawuxUIH0n1UXV3bquQ%2BJaFrtnFQkwvvB3JbAYPYzgWlt6RzDOaRAvM59AeDUkBx&view_type=search&searchType=search&gz=1&t_ref_content=generic&t_ref=search&relayNonce=15c53f6bc93bd153cc19&paid_fl=n&search_uuid=d94edd89-3b03-421a-bb56-a8cbcd178094&immediately_apply_layer_open=n#seq=0",
  "companyname": "(주)디더블유아이"
},
{
  "title": "[세종시] 컴퓨터 유지보수 경력자 모집(관공서 상주)",
  "startdate": "2024-06-23T13:00:00.000Z",
  "enddate": null,
  "resultdate": null,
  "pic1": "",
  "pic2": "",
  "pic3": "",
  "pic4": "",
  "pic5": "",
  "body": "(주)청우정보기술은 세종시에서 관공서 상주 컴퓨터 유지보수를 담당할 경력직 직원을 모집합니다. 다양한 혜택과 함께 지원 가능합니다.",
  "experience": "경력 3~10년",
  "education": "고졸 이상",
  "stack": "SE, 정보통신, H/W",
  "qualification": "경력 10년이하(대리, 과장, 팀원)",
  "preferences": "컴퓨터공학, 정보처리기사, PC정비사 1/2급",
  "work_type": "정규직",
  "salary": "협의 후 결정",
  "location": "세종특별자치시",
  "work_time": "주 5일(월~금) 09:00~18:00",
  "recruit_part": "컴퓨터 유지보수",
  "duties": "컴퓨터 유지보수 및 관리, 관련 기술 지원",
  "key_skills": "컴퓨터 유지보수 및 관리 경력",
  "recruit_num": 1,
  "link": "https://www.saramin.co.kr/zf_user/jobs/relay/view?isMypage=no&rec_idx=48460872&recommend_ids=eJxNj8sRQzEIA6vJHSwh4XMKSf9d5H1mbB8XDWJhK0bAv878%2BMuGk54LRSdu1IPloHlhvGlZjoWUcaYJqfbuROmoiuDohawuxUIH0n1UXV3bquQ%2BJaFrtnFQkwvvB3JbAYPYzgWlt6RzDOaRAvM59AeDUkBx&view_type=search&searchType=search&gz=1&t_ref_content=generic&t_ref=search&relayNonce=15c53f6bc93bd153cc19&paid_fl=n&search_uuid=d94edd89-3b03-421a-bb56-a8cbcd178094&immediately_apply_layer_open=n#seq=0",
  "companyname": "(주)청우정보기술"
},
{
  "title": "정보보호시스템 및 N/W 유지관리 상주(세종) 경력직 채용",
  "startdate": "2024-06-14T16:00:00.000Z",
  "enddate": "2024-08-13T23:59:00.000Z",
  "resultdate": null,
  "pic1": "",
  "pic2": "",
  "pic3": "",
  "pic4": "",
  "pic5": "",
  "body": "링크정보통신(주)은 세종시에서 정보보호시스템 및 네트워크 유지관리를 담당할 경력직 직원을 모집합니다. 다양한 혜택과 함께 지원 가능합니다.",
  "experience": "경력 5~15년",
  "education": "초대졸 이상",
  "stack": "정보보호, 정보통신",
  "qualification": "운전가능, 정보통신공사협회 등 인정 고급기술자 이상",
  "preferences": "정보보안기사 자격증 소지자, 군전역간부, 해당직무 근무경험, 운전가능자, 지방근무 가능자, 문서작성 우수자",
  "work_type": "정규직",
  "salary": "면접 후 결정",
  "location": "세종특별자치시",
  "work_time": "주 5일(월~금) 09:00~18:00",
  "recruit_part": "정보보호시스템 및 네트워크 유지관리",
  "duties": "정보보호시스템 및 네트워크 유지관리, 관련 기술 지원",
  "key_skills": "정보보호시스템 및 네트워크 유지관리 경력",
  "recruit_num": 1,
  "link": "https://www.saramin.co.kr/zf_user/jobs/relay/view?isMypage=no&rec_idx=48408296&recommend_ids=eJxNj8sRQzEIA6vJHSwh4XMKSf9d5H1mbB8XDWJhK0bAv878%2BMuGk54LRSdu1IPloHlhvGlZjoWUcaYJqfbuROmoiuDohawuxUIH0n1UXV3bquQ%2BJaFrtnFQkwvvB3JbAYPYzgWlt6RzDOaRAvM59AeDUkBx&view_type=search&searchType=search&gz=1&t_ref_content=generic&t_ref=search&relayNonce=15c53f6bc93bd153cc19&paid_fl=n&search_uuid=d94edd89-3b03-421a-bb56-a8cbcd178094&immediately_apply_layer_open=n#seq=0",
  "companyname": "링크정보통신(주)"
},
{
  "title": "클라우드영업 및 영업지원 신입 및 경력 채용",
  "startdate": "2024-06-10T00:00:00.000Z",
  "enddate": null,
  "resultdate": null,
  "pic1": "",
  "pic2": "",
  "pic3": "",
  "pic4": "",
  "pic5": "",
  "body": "(주)솔리드이엔지는 클라우드 영업 및 영업지원 신입 및 경력 직원을 모집합니다. 다양한 혜택과 함께 지원 가능합니다.",
  "experience": "신입·경력(년수무관)",
  "education": "학력무관",
  "stack": "정보통신, JAVA, AWS",
  "qualification": "공통 - 클라우드 기술 영업 및 영업지원",
  "preferences": "관련학과, 공공기관 IT사업 유경험자, SI 사업 및 사업관리",
  "work_type": "정규직",
  "salary": "협의 후 결정",
  "location": "세종특별자치시",
  "work_time": "주 5일(월~금) 09:00~18:00",
  "recruit_part": "클라우드영업 및 영업지원",
  "duties": "클라우드 영업 및 영업지원",
  "key_skills": "클라우드 기술, AWS",
  "recruit_num": 1,
  "link": "https://www.saramin.co.kr/zf_user/jobs/relay/view?isMypage=no&rec_idx=48369538&recommend_ids=eJxNj8sNxEAIQ6vZO1%2BbOaeQ9N%2FFkkQa5sbDljFRCYH4XSo%2FXlFI1GIjPrTAikZ9MSnBGLOjd2MOqq9RxcR5JBOUjZHP6eMQabYxRcJqo1ODa9TW8yipDuROznKj7s7QlqcVRZRH5374VT9z9CCTnAldTw39A4fbQIQ%3D&view_type=search&searchType=search&gz=1&t_ref_content=generic&t_ref=search&relayNonce=2bd43038ab40da001482&paid_fl=n&search_uuid=d94edd89-3b03-421a-bb56-a8cbcd178094&immediately_apply_layer_open=n#seq=0",
  "companyname": "(주)솔리드이엔지"
},
{
  "title": "[웹개발] 세종시 공공 프로젝트 개발자 채용 공고",
  "startdate": "2024-07-05T23:00:00.000Z",
  "enddate": "2024-08-04T23:59:00.000Z",
  "resultdate": null,
  "pic1": "",
  "pic2": "",
  "pic3": "",
  "pic4": "",
  "pic5": "",
  "body": "(주)지엠코퍼레이션은 세종시 공공 프로젝트를 위해 웹개발 경력 직원을 모집합니다. 다양한 혜택과 함께 지원 가능합니다.",
  "experience": "경력 3~15년",
  "education": "학력무관",
  "stack": "JAVA, JSP, MYSQL",
  "qualification": "공통 - 웹개발 및 서버개발 경험",
  "preferences": "관련학과, 공공기관 프로젝트 유경험자",
  "work_type": "정규직, 계약직, 프리랜서",
  "salary": "면접 후 결정",
  "location": "세종특별자치시",
  "work_time": "주 5일(월~금) 09:00~18:00",
  "recruit_part": "웹개발",
  "duties": "웹개발 및 서버 개발",
  "key_skills": "JAVA, JSP, MYSQL",
  "recruit_num": 1,
  "link": "https://www.saramin.co.kr/zf_user/jobs/relay/view?isMypage=no&rec_idx=48556198&recommend_ids=eJxNj7cRA0AIBKtRjr2DWIWo%2Fy6EzDwfLuZYoqAO5KtUH3xGZblRF6FBGcQfBeKLImE1KF90znCfLhLVXLRAx%2B5SgotwTO3SSEkeRBKXBkWUeTDyI7bJ7Yk%2BVtD5sDfKSLPdnbpch0b6Gs4J%2Bf37BouPQI4%3D&view_type=search&searchType=search&gz=1&t_ref_content=generic&t_ref=search&relayNonce=c9891032ae4aa5c45b22&paid_fl=n&search_uuid=51201e46-5cd6-4b38-adfc-7bef3d982eee&immediately_apply_layer_open=n#seq=0",
  "companyname": "(주)지엠코퍼레이션"
},
{
  "title": "[플랜아이] 지식 서비스 데이터 이관, Java 개발자 모집",
  "startdate": "2024-07-08T19:00:00.000Z",
  "enddate": "2024-08-07T23:59:00.000Z",
  "resultdate": null,
  "pic1": "",
  "pic2": "",
  "pic3": "",
  "pic4": "",
  "pic5": "",
  "body": "(주)플랜아이는 세종시에서 지식 서비스 데이터 이관을 위한 Java 개발자를 모집합니다. 다양한 혜택과 함께 지원 가능합니다.",
  "experience": "경력 5~10년",
  "education": "대졸(4년제) 이상",
  "stack": "JAVA, 데이터마이닝",
  "qualification": "Java 개발 및 데이터 이관 경험",
  "preferences": "관련학과, 공공기관 프로젝트 유경험자",
  "work_type": "계약직 (3개월, 정규직 전환 가능)",
  "salary": "협의 후 결정",
  "location": "세종특별자치시",
  "work_time": "주 5일(월~금) 09:00~18:00",
  "recruit_part": "데이터 이관 및 Java 개발",
  "duties": "지식 서비스 데이터 이관 및 Java 개발",
  "key_skills": "Java, 데이터마이닝, SI·시스템통합",
  "recruit_num": 1,
  "link": "https://www.saramin.co.kr/zf_user/jobs/relay/view?isMypage=no&rec_idx=48569338&recommend_ids=eJxNj7cRA0AIBKtRjr2DWIWo%2Fy6EzDwfLuZYoqAO5KtUH3xGZblRF6FBGcQfBeKLImE1KF90znCfLhLVXLRAx%2B5SgotwTO3SSEkeRBKXBkWUeTDyI7bJ7Yk%2BVtD5sDfKSLPdnbpch0b6Gs4J%2Bf37BouPQI4%3D&view_type=search&searchType=search&gz=1&t_ref_content=generic&t_ref=search&relayNonce=c9891032ae4aa5c45b22&paid_fl=n&search_uuid=51201e46-5cd6-4b38-adfc-7bef3d982eee&immediately_apply_layer_open=n#seq=0",
  "companyname": "(주)플랜아이"
},
{
  "title": "솔루션 기반 SI사업 PM 모집",
  "startdate": "2024-07-11T11:00:00.000Z",
  "enddate": "2024-08-11T18:00:00.000Z",
  "resultdate": null,
  "pic1": "",
  "pic2": "",
  "pic3": "",
  "pic4": "",
  "pic5": "",
  "body": "(주)바이브컴퍼니는 세종시에서 솔루션 기반 SI사업 PM을 모집합니다. 다양한 혜택과 함께 지원 가능합니다.",
  "experience": "경력 8년 이상",
  "education": "학력무관",
  "stack": "JAVA, 빅데이터, DBMS",
  "qualification": "SI사업 PM 경력 8년 이상",
  "preferences": "PMP 자격 보유자, 외부 감리 대응경험",
  "work_type": "정규직 (수습기간 3개월)",
  "salary": "면접 후 결정",
  "location": "세종특별자치시",
  "work_time": "주 5일(월~금) 09:00~18:00 (시차출근제 운영 중)",
  "recruit_part": "SI사업 PM",
  "duties": "솔루션 기반 SI사업 프로젝트 관리",
  "key_skills": "Java, SI개발, 빅데이터, 개발PM, DBMS",
  "recruit_num": 1,
  "link": "https://vaiv-team.career.greetinghr.com/o/118911",
  "companyname": "(주)바이브컴퍼니"
},
{
  "title": "[정규직] 자율주행 성능평가(3D 가상시뮬레이션) 경력자 채용",
  "startdate": "2024-07-16T17:00:00.000Z",
  "enddate": "2024-08-15T23:59:00.000Z",
  "resultdate": null,
  "pic1": "",
  "pic2": "",
  "pic3": "",
  "pic4": "",
  "pic5": "",
  "body": "(주)오토노머스에이투지는 자율주행 성능평가(3D 가상시뮬레이션) 경력자를 모집합니다. 다양한 혜택과 함께 지원 가능합니다.",
  "experience": "경력 3년 이상",
  "education": "대졸(4년제) 이상",
  "stack": "Unity, 자율주행, 정보통신",
  "qualification": "대졸이상 (4년), Unity 엔진을 이용한 3D 개발경험 3년이상",
  "preferences": "MORAI Simulation 사용 경험자, 자율주행 관련 업계 종사자",
  "work_type": "정규직 (수습기간 3개월)",
  "salary": "면접 후 결정",
  "location": "세종특별자치시",
  "work_time": "주 5일(월~금) 09:00~18:00",
  "recruit_part": "자율주행 성능평가(3D 가상시뮬레이션)",
  "duties": "자율주행 성능평가 및 관련 기술 지원",
  "key_skills": "자율주행 성능평가 경력",
  "recruit_num": 1,
  "link": "https://www.saramin.co.kr/zf_user/jobs/relay/view?isMypage=no&rec_idx=48624860&recommend_ids=eJxNj8sRQzEIA6vJHSwh4XMKSf9d5H1mbB8XDWJhK0bAv878%2BMuGk54LRSdu1IPloHlhvGlZjoWUcaYJqfbuROmoiuDohawuxUIH0n1UXV3bquQ%2BJaFrtnFQkwvvB3JbAYPYzgWlt6RzDOaRAvM59AeDUkBx&view_type=search&searchType=search&gz=1&t_ref_content=generic&t_ref=search&relayNonce=15c53f6bc93bd153cc19&paid_fl=n&search_uuid=d94edd89-3b03-421a-bb56-a8cbcd178094&immediately_apply_layer_open=n#seq=0",
  "companyname": "(주)오토노머스에이투지"
},
{
  "title": "(SI/SM) JAVA 신입 웹프로그래머(개발자, 세종 근무) 모집",
  "startdate": "2024-07-31T17:00:00.000Z",
  "enddate": "2024-08-11T23:59:00.000Z",
  "resultdate": null,
  "pic1": "",
  "pic2": "",
  "pic3": "",
  "pic4": "",
  "pic5": "",
  "body": "(주)에이치지는 세종특별자치시에서 (SI/SM) JAVA 신입 웹프로그래머(개발자)를 모집합니다. 다양한 혜택과 함께 지원 가능합니다.",
  "experience": "경력(년수무관)",
  "education": "대졸(2,3년제) 이상",
  "stack": "JAVA, 서버개발, 클라우드",
  "qualification": "신입 가능, 대졸(2,3년제) 이상",
  "preferences": "해당직무 경험자 우대, 클라우드 경험자 우대",
  "work_type": "정규직, 계약직 (정규직 전환 가능, 수습기간 3개월)",
  "salary": "협의 후 결정",
  "location": "세종특별자치시",
  "work_time": "주 5일(월~금) 09:00~18:00",
  "recruit_part": "(SI/SM) JAVA 신입 웹프로그래머(개발자)",
  "duties": "JAVA 기반 웹프로그래밍 및 유지보수",
  "key_skills": "Java, 웹개발, 백엔드/서버개발, 클라우드",
  "recruit_num": 1,
  "link": "https://www.saramin.co.kr/zf_user/jobs/relay/view?isMypage=no&rec_idx=48721181&recommend_ids=eJxNj7sRA0EIQ6txvgJWgtiFuP8uzJ09y4UafXhE0jywPon10jtyc5tVS%2FwkJOXDRegK85asovaROwrwCXfU%2FLjByNQsO3F3%2F2GY1mM5UtCTKn2W6Q1dEzYv1XGjMcihQtTidEPwebCP5p4X2mQNRl814ep%2BAYABQH4%3D&view_type=search&searchType=search&gz=1&t_ref_content=generic&t_ref=search&relayNonce=717ea0c6be2ff29f3837&paid_fl=n&search_uuid=8448a9e3-17f8-40ac-8cd2-df291b5a4f73&immediately_apply_layer_open=n#seq=0",
  "companyname": "(주)에이치지"
},
{
  "title": "SW개발 팀장급 정규직 채용",
  "startdate": "2024-07-05T16:00:00.000Z",
  "enddate": null,
  "resultdate": null,
  "pic1": "",
  "pic2": "",
  "pic3": "",
  "pic4": "",
  "pic5": "",
  "body": "㈜에세텔은 세종특별자치시에서 SW개발 팀장급 정규직을 모집합니다. 다양한 혜택과 함께 지원 가능합니다.",
  "experience": "경력 10년 이상",
  "education": "대졸(4년제) 이상",
  "stack": "JAVA, C++, JavaScript",
  "qualification": "SW 개발업무 2년 이상, 대졸이상",
  "preferences": "컴퓨터/시스템공학 전공자, 정보처리기사, 정보처리산업기사",
  "work_type": "정규직 (수습기간 3개월)",
  "salary": "면접 후 결정",
  "location": "세종특별자치시, 대전유성구, 대전전체",
  "work_time": "주 5일(월~금) 09:00~18:00",
  "recruit_part": "SW개발 팀장",
  "duties": "SW개발 팀장으로서 SW개발 프로젝트 관리 및 수행",
  "key_skills": "웹개발, Java, C++, 프론트엔드, Javascript",
  "recruit_num": 1,
  "link": "https://www.saramin.co.kr/zf_user/jobs/relay/view?isMypage=no&rec_idx=48554312&recommend_ids=eJxNj7sRA0EIQ6txvgJWgtiFuP8uzJ09y4UafXhE0jywPon10jtyc5tVS%2FwkJOXDRegK85asovaROwrwCXfU%2FLjByNQsO3F3%2F2GY1mM5UtCTKn2W6Q1dEzYv1XGjMcihQtTidEPwebCP5p4X2mQNRl814ep%2BAYABQH4%3D&view_type=search&searchType=search&gz=1&t_ref_content=generic&t_ref=search&relayNonce=717ea0c6be2ff29f3837&paid_fl=n&search_uuid=8448a9e3-17f8-40ac-8cd2-df291b5a4f73&immediately_apply_layer_open=n#seq=0",
  "companyname": "㈜에세텔"
},
{
  "title": "[코스닥 상장 스타트업]S/W 개발 및 운영",
  "startdate": "2024-07-18T10:00:00.000Z",
  "enddate": "2024-08-17T23:59:00.000Z",
  "resultdate": "",
  "pic1": "",
  "pic2": "",
  "pic3": "",
  "pic4": "",
  "pic5": "",
  "body": "㈜아츠코리아는 서울 강남구 및 세종특별자치시에서 S/W 개발 및 운영 경력자를 모집합니다. 다양한 혜택과 함께 지원 가능합니다.",
  "experience": "경력 3년 이상",
  "education": "대졸(4년제) 이상",
  "stack": "C++, RTOS, C언어",
  "qualification": "경력 3년 이상, 대졸(4년제) 이상",
  "preferences": "RTOS(실시간 운영체계) 및 HILS 개발 경험자, 컴파일러 이론 이해",
  "work_type": "정규직",
  "salary": "면접 후 결정",
  "location": "세종특별자치시, 서울 강남구",
  "work_time": "주 5일(월~금) 09:00~18:00",
  "recruit_part": "S/W 개발 및 운영",
  "duties": "S/W 개발 및 운영 업무 수행",
  "key_skills": "S/W, C++, RTOS, Windows, C언어",
  "recruit_num": 1,
  "link": "https://www.saramin.co.kr/zf_user/jobs/relay/view?isMypage=no&rec_idx=48636416&recommend_ids=eJxNj7sRA0EIQ6txvgJWgtiFuP8uzJ09y4UafXhE0jywPon10jtyc5tVS%2FwkJOXDRegK85asovaROwrwCXfU%2FLjByNQsO3F3%2F2GY1mM5UtCTKn2W6Q1dEzYv1XGjMcihQtTidEPwebCP5p4X2mQNRl814ep%2BAYABQH4%3D&view_type=search&searchType=search&gz=1&t_ref_content=generic&t_ref=search&relayNonce=717ea0c6be2ff29f3837&paid_fl=n&search_uuid=0012243d-c22b-42e4-a893-d712a136b928&immediately_apply_layer_open=n#seq=0",
  "companyname": "㈜아츠코리아"
},
{
  "title": "국내 반도체 제조 기업 windows application 개발",
  "startdate": "2024-07-24T13:00:00.000Z",
  "enddate": "2024-08-23T23:59:00.000Z",
  "resultdate": null,
  "pic1": "https://pds.saramin.co.kr/workenv-bg/202407/19/sguiqo_162l-1a0yb38_workenv-bg.png",
  "pic2": "https://pds.saramin.co.kr/workenv-bg/202306/02/rvltzv_nfdr-1a0yb3h_workenv-bg.png",
  "pic3": "https://pds.saramin.co.kr/workenv-bg/202406/12/seyavk_hhjo-1a0yb3h_workenv-bg.png",
  "pic4": "",
  "pic5": "",
  "body": "㈜맨파워코리아는 세종특별자치시에서 Windows Application 개발 경력자를 모집합니다. 다양한 혜택과 함께 지원 가능합니다.",
  "experience": "경력 4년 이상",
  "education": "대졸(4년제) 이상",
  "stack": "C++, C#, Windows",
  "qualification": "경력 4년 이상, 대졸(4년제) 이상",
  "preferences": "반도체 관련 경험자 우대, 기계/기구 제어 SW 개발 경력자",
  "work_type": "정규직 (수습기간 3개월)",
  "salary": "협의 후 결정",
  "location": "세종특별자치시",
  "work_time": "주 5일(월~금) 09:00~18:00",
  "recruit_part": "Windows Application 개발",
  "duties": "Windows Application 개발 및 유지보수",
  "key_skills": "C++, C#, Windows, 앱개발, 반도체",
  "recruit_num": 1,
  "link": "https://www.saramin.co.kr/zf_user/jobs/relay/view?isMypage=no&rec_idx=48676407&recommend_ids=eJxNj7sRA0EIQ6txvgJWgtiFuP8uzJ09y4UafXhE0jywPon10jtyc5tVS%2FwkJOXDRegK85asovaROwrwCXfU%2FLjByNQsO3F3%2F2GY1mM5UtCTKn2W6Q1dEzYv1XGjMcihQtTidEPwebCP5p4X2mQNRl814ep%2BAYABQH4%3D&view_type=search&searchType=search&gz=1&t_ref_content=generic&t_ref=search&relayNonce=717ea0c6be2ff29f3837&paid_fl=n&search_uuid=eae50593-083e-44a0-b762-93e711910dfb&immediately_apply_layer_open=n#seq=0",
  "companyname": "㈜맨파워코리아"
},
{
  "title": "마스코리아(주) 생산/품질관리 신입사원 채용(세종)",
  "startdate": "2024-06-26T14:00:00.000Z",
  "enddate": "2024-08-25T23:59:00.000Z",
  "resultdate": null,
  "pic1": "",
  "pic2": "",
  "pic3": "",
  "pic4": "",
  "pic5": "",
  "body": "마스코리아(주)는 세종특별자치시에서 생산 및 품질관리 신입사원을 모집합니다. 다양한 혜택과 함께 지원 가능합니다.",
  "experience": "무관(신입포함)",
  "education": "고졸 이상",
  "stack": "임베디드, 펌웨어",
  "qualification": "무관(신입포함), 고졸 이상",
  "preferences": "전기/전자공학, 컴퓨터/시스템공학, 기계/자동차/조선공학 전공자, 토목기사, AutoCAD 자격증 소지자, 영어 가능자, 컴퓨터 활용능력 우수자, 문서작성 우수자, CAD/CAM 능숙자, 인근 거주자, 해당직무 근무 경험자",
  "work_type": "정규직 (수습기간 3개월)",
  "salary": "면접 후 결정",
  "location": "세종특별자치시",
  "work_time": "주 5일(월~금) 09:00~18:00",
  "recruit_part": "생산/품질관리",
  "duties": "생산 및 품질관리 업무 수행",
  "key_skills": "임베디드, 펌웨어, 생산관리, QA, QC",
  "recruit_num": 1,
  "link": "https://www.saramin.co.kr/zf_user/jobs/relay/view?isMypage=no&rec_idx=48485849&view_type=search&searchType=search&gz=1&t_ref_content=generic&t_ref=search&relayNonce=717ea0c6be2ff29f3837&paid_fl=n&search_uuid=eae50593-083e-44a0-b762-93e711910dfb&immediately_apply_layer_open=n#seq=0",
  "companyname": "마스코리아(주)"
}
];

// 데이터베이스 시딩 함수
async function realRecruitment() {
  try {
    // 데이터베이스 연결 확인
    await sequelize.authenticate();

    // 채용 공고 데이터 삽입
    await RecruitmentNoticeInfo.bulkCreate(recruitmentNotices, { ignoreDuplicates: true });
    console.log('채용 공고가 성공적으로 삽입되었습니다.');

    console.log('데이터베이스 시딩이 완료되었습니다.');
  } catch (error) {
    console.error('데이터베이스 시딩 중 오류 발생:', error);
  } finally {
    // 데이터베이스 연결 종료
    await sequelize.close();
    console.log('데이터베이스 연결이 종료되었습니다.');
  }
}

// 시딩 함수 실행
realRecruitment();