const { sequelize } = require('./config/db');
const Company = require('./models/Company/company');

const companies = [
    {
        "companyName": "(주)어빌리티시스템즈",
        "establish": "2004-07-07",
        "logo": "https://pds.saramin.co.kr/company/logo/201902/25/pnhbeo_joeh-0_logo.jpg",
        "pic1": "https://cdn.jumpit.co.kr/lg/images/5898/20243829143833931_896_512.webp",
        "pic2": "",
        "pic3": "",
        "pic4": "",
        "pic5": "",
        "body": "(주)어빌리티시스템즈는 2004년 설립되어 2022년 기준 매출액 570억원을 달성하여 전년대비 높은 성장률을 기록하였습니다. 당사는 SI/NI 외 네트워크장비 유통 총판 사업, IoT회선서비스 사업, 개발사업이 주력인 회사입니다.",
        "track": "백엔드",
        "stack": "JAVA, JavaScript, jQuery, Spring, Oracle, MYSQL, PostgreSQL",
        "welfare": "지원금/보험, 교육/생활, 출퇴근, 급여제도, 근무 환경, 리프레쉬",
        "salary": "협의 후 결정",
        "location": "",
        "employee": "105명",
        "link": "http://www.abilsys.com",
        "revenue": null
      },
      {
        "companyName": "(주)체스트넛",
        "establish": "2020-09-21",
        "logo": "https://pds.saramin.co.kr/company/logo/202306/09/rvzg5s_g8v0-1mrhl7t_logo.png",
        "pic1": "https://pds.saramin.co.kr/workenv-bg/202307/29/ryk70m_3b02-1mgs1i4_workenv-bg.png",
        "pic2": "",
        "pic3": "",
        "pic4": "",
        "pic5": "",
        "body": "체스트넛은 Web/Apps 개발 사업 및 자문, SI/SM Team Project Outsourcing을 하는 IT기업입니다. 다양한 비즈니스 영역에 플랫폼을 개발하고 세상을 편리하고 스마트하게 만드는데 일조하고자 합니다.",
        "track": "풀스택",
        "stack": "JAVA, JSP, SQL, React, Vue",
        "welfare": "지원금/보험, 교육/생활, 출퇴근, 급여제도, 근무 환경, 리프레쉬",
        "salary": "협의 후 결정",
        "location": "서울 금천구 시흥대로59길 9, 2층 202호",
        "employee": "4명",
        "link": "http://chestnut.kr",
        "revenue": ""
      },
      {
        "companyName": "(주)에스씨정보",
        "establish": "2018-03-29",
        "logo": "https://pds.saramin.co.kr/company/logo/201810/22/pgzojs_hclo-1pwyxm6_logo.png",
        "pic1": "https://search.pstatic.net/sunny/?src=https%3A%2F%2Fimages.unsplash.com%2Fphoto-1590232918080-66313d51bd9f%3Fixlib%3Drb-4.0.3%26ixid%3DMnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDZ8fHxlbnwwfHx8fA%253D%253D%26w%3D1000%26q%3D80&type=sc960_832",
        "pic2": "",
        "pic3": "",
        "pic4": "",
        "pic5": "",
        "body": "(주)에스씨정보는 2018년 설립된 중소기업으로, 기타 정보기술 및 컴퓨터운영 관련 서비스업을 영위하고 있습니다. 2022년 기준 매출액은 24억원을 기록하였으며, 주요 사업으로는 컴퓨터 유지보수가 있습니다.",
        "track": "네트워크",
        "stack": "방화벽 관리",
        "welfare": "주 5일 근무, 유연한 근무 시간 제도 운영",
        "salary": "연봉 4,000만원(주 40시간)",
        "location": "대전 유성구 은구비남로7번길 61, 303호",
        "employee": "5명",
        "link": "http://scinfo.co.kr/",
        "revenue": "24억원 (2022년 기준)"
      },
      {
        "companyName": "(주)지비티",
        "establish": "2007-01-23",
        "logo": "https://www.sgbt.co.kr/static/img/common/mainLogo.png",
        "pic1": "https://www.sgbt.co.kr/static/img/common/footerLogo.png",
        "pic2": "",
        "pic3": "",
        "pic4": "",
        "pic5": "",
        "body": "(주)지비티는 2007년 설립된 중소기업으로, 경영 컨설팅업을 영위하고 있습니다.",
        "track": "풀스택",
        "stack": "JAVA, C#, JavaScript, Spring, MS-SQL, Oracle, MariaDB, Linux",
        "welfare": "",
        "salary": "평균 연봉 5,912만원",
        "location": "경기 성남시 중원구 둔촌대로 545, B1호",
        "employee": "5명",
        "link": "https://www.sgbt.co.kr/",
        "revenue": ""
      },
      {
        "companyName": "비전세미콘(주)",
        "establish": "2001-03-09",
        "logo": "https://pds.saramin.co.kr/company/logo/201902/27/pnkhuy_gezw-0_logo.gif",
        "pic1": "http://visionsemicon.co.kr/user/attachment/202301/1672888046571906.jpg",
        "pic2": "",
        "pic3": "",
        "pic4": "",
        "pic5": "",
        "body": "비전세미콘은 인류에게 봉사하고 후손에게 존경받는 기업을 표방한다. 기업의 가치는 ‘인류를 위해 무엇을 제공할 것인가’이고 모든 인류에게 행복과 만족을 추구할 수 있도록 해야 한다는 게 이들의 신념이다.",
        "track": "백엔드",
        "stack": "JAVA, C#, JavaScript, Spring, MS-SQL, Oracle, MariaDB, Linux",
        "welfare": "각종 경조사 지원, 체력단련실운영, 퇴직연금, 야근수당, 휴일(특근)수당, 4대 보험, 명절선물/귀향비, 생일선물/파티, 점심식사 제공, 저녁식사 제공, 휴게실, 수면실, 회의실, 전용 사옥, 장애인 화장실, 장애인 전용주차장, 장애인 엘리베이터, 자유복장, 기숙사 운영",
        "salary": "협의 후 결정",
        "location": "세종 집현중앙4로 79",
        "employee": "133명",
        "link": "http://www.visionsemicon.co.kr",
        "revenue": "505억 2,253만원 (2022년 기준)"
      },
      {
        "companyName": "에스휴먼(주)",
        "establish": null,
        "logo": "http://www.s-human.co.kr/wp-content/uploads/2020/07/logo.png",
        "pic1": "http://www.s-human.co.kr/wp-content/uploads/2020/07/vision01.jpg",
        "pic2": "",
        "pic3": "",
        "pic4": "",
        "pic5": "",
        "body": "에스휴먼(주)는 근로자 파견, 헤드헌팅 전문 아웃소싱 기업입니다. 외국계 기업에서 파견 계약직으로 성실히 근무 할 분을 모집중입니다.",
        "track": "",
        "stack": "PC관리",
        "welfare": "각종 경조사 지원, 점심식사 제공, 4대보험, 퇴직금, 성과금, 연차, 휴가 등",
        "salary": "협의 후 결정",
        "location": "대전 대덕구, 대전전체, 동구, 서구, 중구, 세종특별자치시",
        "employee": "",
        "link": "http://www.s-human.co.kr/",
        "revenue": ""
      },
      {
        "companyName": "대신네트웍스(주)",
        "establish": "1991-07-08",
        "logo": "https://pds.saramin.co.kr/company/logo/201902/26/pnj09a_rygz-0_logo.jpg",
        "pic1": "https://postfiles.pstatic.net/MjAyNDA1MTNfMjMw/MDAxNzE1NTc0ODIxNzI5.tbWRVOy-5W_BZMafqCG4MDuRY8DJIaT0YpoDu3W-vzYg.KmxS7zccJRott1-jw5kHrHhZ1PjdpyZlilY0b6QqHe4g.PNG/005.png?type=w966",
        "pic2": "",
        "pic3": "",
        "pic4": "",
        "pic5": "",
        "body": "대신네트웍스(주)은 정보통신공사, 컴퓨터 및 주변기기, 통신장비, 비주거용 건물 임대업(점포, 자기땅), 전산장비임대, 소프트웨어 자문개발, 자료처리업, 전산장비 유지보수용역을 제공하는 중소기업입니다.",
        "track": "백엔드",
        "stack": "Spring, Linux",
        "welfare": "건강검진, 단체 상해보험, 업무활동비 지급, 통신비 지원, 퇴직연금, 상여금",
        "salary": "협의 후 결정",
        "location": "대전 서구 둔산대로117번길 83, 4층",
        "employee": "96명",
        "link": "http://www.dsnw.net",
        "revenue": "236억 4,410만원"
      },
      {
        "companyName": "(주)하랑에듀",
        "establish": "2019-01-29",
        "logo": "https://pds.saramin.co.kr/company/logo/202103/23/qqeq5y_1r3a-h0biql_logo.png",
        "pic1": "https://harangedu.com/images/sub/bg_greeting.png",
        "pic2": "",
        "pic3": "",
        "pic4": "",
        "pic5": "",
        "body": "(주)하랑에듀는 평생교육원, 응용 소프트웨어 개발 및 공급업, 미디어 콘텐츠 창작업을 영위하는 중소기업입니다. 고용노동부 인증 환급과정(사업주위탁훈련 및 국민내일배움카드제)을 운영하며, 산업안전보건교육 위탁기관, 직장 내 장애인 인식개선교육기관 지정을 받아 다양한 법정 교육을 운영하고 있습니다. 또한 LMS 이러닝 시스템 개발 및 유통, 온라인 콘텐츠 제작에 관련하여 도약을 준비하고 있습니다.",
        "track": "백엔드",
        "stack": "PHP, JavaScript, MYSQL, jQuery, Ajax",
        "welfare": "각종 경조사 지원, 점심식사 제공, 4대보험, 퇴직금, 성과금, 연차, 휴가 등",
        "salary": "협의 후 결정",
        "location": "세종 한누리대로 273, 5층 501호 (나성동, 새롬씨티)",
        "employee": "8명",
        "link": "http://www.harangedu.com/",
        "revenue": "6억 2,921만원 (2021년 기준)"
      },
      {
        "companyName": "(주)엠케이코리아",
        "establish": "2011-06-02",
        "logo": "https://pds.saramin.co.kr/company/logo/202407/26/sh7fh4_3xhk-1mnxa0y_logo.png",
        "pic1": "https://www.theteams.kr/includes/uploads/recruit/(%EC%A3%BC)%EC%97%A0%EC%BC%80%EC%9D%B4%EC%BD%94%EB%A6%AC%EC%95%84_202303061.png",
        "pic2": "",
        "pic3": "",
        "pic4": "",
        "pic5": "",
        "body": "(주)엠케이코리아는 알루미늄, 마그네슘 및 신소재 주조업을 영위하는 중소기업입니다. 2011년 설립 이래로 단단하게 성장하고 있으며, 다양한 신소재를 다루고 있습니다.",
        "track": "백엔드",
        "stack": "C#, DevExpress, MS-SQL",
        "welfare": "건강검진, 직원대출제도, 단체 상해보험, 퇴직연금, 인센티브제, 상여금, 성과급, 야근수당, 휴일(특근)수당, 연차수당, 직책수당, 자격증수당, 4대 보험, 명절선물/귀향비, 창립일선물지급, 워크샵, 구내식당(사원식당), 점심식사 제공, 저녁식사 제공, 회의실, 회식강요 안함, 자유복장, 자유로운 연차사용, 기숙사 운영, 통근버스 운행, 회사차량 있음, 연차, 여름휴가, 반차, 근로자의 날 휴무, 공휴일 휴무",
        "salary": "협의 후 결정",
        "location": "세종 전동면 노장공단길 18",
        "employee": "31명",
        "link": "http://www.mkkorea.kr/index.php",
        "revenue": "94억 449만원"
      },
      {
        "companyName": "(주)공감아이티",
        "establish": "2015-11-26",
        "logo": "https://pds.saramin.co.kr/company/logo/201902/27/pnkjz7_2tyf-0_logo.png",
        "pic1": "http://kongam.co.kr/resources/images/2022/cs-img-1.jpg",
        "pic2": "",
        "pic3": "",
        "pic4": "",
        "pic5": "",
        "body": "(주)공감아이티는 고객, 직원, 조직과의 공감ㆍ 소통을 중요시하는 정보기술 서비스 전문기업입니다. 다수의 지자체 및 공공기관을 대상으로 위치기반 기술을 응용한 맞춤형 솔루션을 개발하여 공급하고 있으며, GIS분야의 독보적인 자체 기술을 보유하고 있습니다.",
        "track": "백엔드",
        "stack": "JAVA, Spring, MYSQL, JavaScript",
        "welfare": "건강검진, 직원대출제도, 단체 상해보험, 퇴직연금, 인센티브제, 상여금, 성과급, 야근수당, 휴일(특근)수당, 연차수당, 직책수당, 자격증수당, 4대 보험, 명절선물/귀향비, 창립일선물지급, 워크샵, 구내식당(사원식당), 점심식사 제공, 저녁식사 제공, 회의실, 회식강요 안함, 자유복장, 자유로운 연차사용, 기숙사 운영, 통근버스 운행, 회사차량 있음, 연차, 여름휴가, 반차, 근로자의 날 휴무, 공휴일 휴무",
        "salary": "협의 후 결정",
        "location": "충남 계룡시 서금암3길 5, 206호 (금암동,쉐리움오피스텔)",
        "employee": "36명",
        "link": "http://kongam.co.kr/",
        "revenue": "43억 9,581만원"
      },
      {
        "companyName": "(주)엑스코어시스템",
        "establish": "2017-01-11",
        "logo": "https://pds.saramin.co.kr/company/logo/202001/28/q4ss9n_amfd-xrtaj0_logo.png",
        "pic1": "https://www.xcs.co.kr/static/recruit/saramin/image/room1.jpg",
        "pic2": "https://www.xcs.co.kr/static/recruit/saramin/image/room5.jpg",
        "pic3": "https://www.xcs.co.kr/static/recruit/saramin/image/room3.jpg",
        "pic4": "https://www.xcs.co.kr/static/recruit/saramin/image/room4.jpg",
        "pic5": "",
        "body": "(주)엑스코어시스템은 컴퓨터시스템 통합 자문 및 구축 서비스, 소프트웨어 개발, 전자부품 제조 등 다양한 사업을 영위하는 중소기업입니다. 주요 공공 시스템과 IoT 센서 관련 솔루션을 제공하며, 국내외 시장에서 매년 50% 이상의 성장을 이루고 있습니다.",
        "track": "백엔드",
        "stack": "JAVA, Spring, MYSQL, JavaScript",
        "welfare": "건강검진, 직원대출제도, 단체 상해보험, 퇴직연금, 인센티브제, 상여금, 성과급, 야근수당, 휴일(특근)수당, 연차수당, 직책수당, 자격증수당, 4대 보험, 명절선물/귀향비, 창립일선물지급, 워크샵, 구내식당(사원식당), 점심식사 제공, 저녁식사 제공, 회의실, 회식강요 안함, 자유복장, 자유로운 연차사용, 기숙사 운영, 통근버스 운행",
        "salary": "협의 후 결정",
        "location": "세종 집현중앙7로 6, 비동 501호, 502호 503호, 504호, 505호, 506호, 507호, 508호, 512호, 513호, 516호, 517호, 518호, 519호",
        "employee": "46명",
        "link": "http://www.xcs.co.kr",
        "revenue": "68억 7,695만원"
      },
      {
        "companyName": "지엔소프트(주)",
        "establish": "2007-01-18",
        "logo": "https://pds.saramin.co.kr/company/logo/202007/08/qd4mfp_j94v-1p4pzp0_logo.jpg",
        "pic1": "https://cdn.hellodd.com/news/photo/202206/97311_313113_038.png",
        "pic2": "",
        "pic3": "",
        "pic4": "",
        "pic5": "",
        "body": "지엔소프트(주)는 소프트웨어 개발, 정보통신공사, 컴퓨터 및 주변장치 도소매, 컴퓨터시스템 통합 자문 및 구축, 자료처리, 데이터베이스, 온라인 정보 제공 등을 전문으로 하는 중소기업입니다. 통계시스템 및 자료구축 분야에서 전문성을 가지고 있습니다.",
        "track": "백엔드",
        "stack": "JAVA, JSP, SQL",
        "welfare": "건강검진, 각종 경조사 지원, 업무활동비 지급, 문화생활비, 퇴직연금, 상여금",
        "salary": "협의 후 결정",
        "location": "대전 유성구 문지로 272-16, 201호.202호.203호.204호.205호 (문지동,에이아이인공지능센터)",
        "employee": "121명",
        "link": "http://www.gn-soft.co.kr",
        "revenue": "128억 4,874만원"
      },
      {
        "companyName": "(주)컴트루테크놀로지",
        "establish": "1997-04-08",
        "logo": "https://pds.saramin.co.kr/company/logo/202302/06/rpnbje_1zbg-1crlcu9_logo.jpg",
        "pic1": "https://img.youtube.com/vi/v1FT-8LqyQg/mqdefault.jpg",
        "pic2": "",
        "pic3": "",
        "pic4": "",
        "pic5": "",
        "body": "컴트루테크놀로지는 인공지능 및 정보보안(개인정보보호) 기술을 자체적으로 개발하고 이를 활용한 소프트웨어를 제공하는 벤더사입니다.",
        "track": "시스템 소프트웨어 개발",
        "stack": "Linux, Ubuntu, RedHat",
        "welfare": "역세권, 지원금/보험제도, 급여제도, 선물, 교육/생활 혜택 등",
        "salary": "협의 후 결정",
        "location": "서울 마포구 매봉산로 45, 10층",
        "employee": "",
        "link": "http://www.comtrue.com",
        "revenue": "29억 2,954만원"
      },
      {
        "companyName": "주식회사케이소프트",
        "establish": null,
        "logo": "http://k-soft.co.kr/images/logo.gif",
        "pic1": "http://k-soft.co.kr/images/sample-event.jpg",
        "pic2": "http://k-soft.co.kr/images/sample-image.jpg",
        "pic3": "",
        "pic4": "",
        "pic5": "",
        "body": "주식회사케이소프트는 정보보안 솔루션을 제공하는 기업으로, 정보보안 유지관리 엔지니어를 채용합니다. 다양한 혜택과 함께 경력 무관하게 지원 가능합니다.",
        "track": "정보보호",
        "stack": "정보보호",
        "welfare": "지원금/보험제도, 급여제도, 선물, 교육/생활 혜택 등",
        "salary": "협의 후 결정",
        "location": "세종 집현중앙7로 6 지식산업센터",
        "employee": "",
        "link": "http://k-soft.co.kr/index.do",
        "revenue": ""
      },
      {
        "companyName": "상상스토리(주)",
        "establish": "2005-04-14",
        "logo": "https://pds.saramin.co.kr/company/logo/201902/27/pnkk12_o30a-0_logo.jpg",
        "pic1": "https://imgs.jobkorea.co.kr/img3/_thumb/0x390/Company/Visual_Co/images/2018/2/JK_CO_emsis0314_2.jpg",
        "pic2": "https://imgs.jobkorea.co.kr/img3/_thumb/0x390/Company/Visual_Co/images/2018/2/JK_CO_emsis0314_3.jpg",
        "pic3": "",
        "pic4": "",
        "pic5": "",
        "body": "상상스토리(주)는 교육컨텐츠 및 소프트웨어 개발, 기업위탁교육 등을 제공하는 중견기업입니다. 다양한 혜택과 함께 경력 개발자를 채용합니다.",
        "track": "백엔드",
        "stack": "JAVA, JSP",
        "welfare": "지원금/보험제도, 급여제도, 선물, 교육/생활 혜택 등",
        "salary": "협의 후 결정",
        "location": "서울 구로구 디지털로 288, 2006호 (구로동,대륭포스트타워1차)",
        "employee": "75명",
        "link": "http://www.sangs.co.kr",
        "revenue": "74억 1,558만원"
      },
      {
        "companyName": "아이리스인포테크주식회사",
        "establish": "2009-08-14",
        "logo": "https://www.irisinfotech.co.kr/images/2020/iris_index_update_irislogo.png",
        "pic1": "https://www.irisinfotech.co.kr/images/share-img.jpg",
        "pic2": "https://www.eventservice.kr/2020/HPE/00/eDM_1026_IRIS_04.png",
        "pic3": "",
        "pic4": "",
        "pic5": "",
        "body": "아이리스인포테크주식회사는 외국계 제약회사의 전산 및 네트워크 장비 도매 및 설치, 유지보수를 목적으로 창업된 중소기업입니다. 지속적인 투자와 인재 개발을 통해 성장하고 있으며, 고객과 함께 발전하는 기업입니다.",
        "track": "네트워크",
        "stack": "VMware, vSAN",
        "welfare": "퇴직금, 4대 보험, 회식강요 안함",
        "salary": "협의 후 결정",
        "location": "서울 마포구 성암로 330, 5층 513호 (상암동, 디엠씨첨단산업센터)",
        "employee": "70명",
        "link": "https://www.irisinfotech.co.kr",
        "revenue": "154억 6,058만원"
      },
      {
        "companyName": "(주)씨앤",
        "establish": "2023-05-15",
        "logo": "https://pds.saramin.co.kr/company/logo/202206/03/rcwa52_gnns-xn8ewl_logo.png",
        "pic1": "https://pds.saramin.co.kr/workenv-bg/202406/12/sey4jc_87fp-xn8ewl_workenv-bg.jpg",
        "pic2": "",
        "pic3": "",
        "pic4": "",
        "pic5": "",
        "body": "(주)씨앤은 유·무선 통신장비, CCTV, 주차관제 및 출입통제 장비를 제조하는 중소기업입니다. 다양한 산업 분야에서 자동화 및 자동제어 시스템을 제공하며, 지속적인 성장을 추구하고 있습니다.",
        "track": "네트워크",
        "stack": "네트워크, 정보통신",
        "welfare": "퇴직금, 4대 보험",
        "salary": "연봉 3,200 만원 (주 40시간)",
        "location": "세종 집현중앙7로 6, A동 902호 (집현동,지식산업센터)",
        "employee": "8명",
        "link": "http://www.sea-n.co.kr/wp_main/index.html",
        "revenue": "6억 263만원"
      },
      {
        "companyName": "(주)디더블유아이",
        "establish": "2007-12-28",
        "logo": "https://pds.saramin.co.kr/company/logo/201902/27/pnk6yc_w73q-0_logo.jpg",
        "pic1": "https://www.dwni.co.kr/ko/data/ebcontents/eb4_busi_026/img/1f2876c4f63413e5f807b945b604432c.jpg",
        "pic2": "",
        "pic3": "",
        "pic4": "",
        "pic5": "",
        "body": "디더블유아이는 자사 솔루션 기반으로 작지만 탄탄하게 성장하고 있는 시설관리솔루션과 환자이송솔루션 자체 개발 기업입니다. 지속적인 성장과 수많은 고객들을 확보하고 있으며 보유하고 있는 솔루션을 고도화하여 시장확대를 준비하고 있습니다. 많은 관심을 부탁드립니다.",
        "track": "시스템 소프트웨어 개발",
        "stack": "JAVA, Linux, CUBRID",
        "welfare": "퇴직연금, 인센티브제, 장기근속자 포상, 우수사원포상, 퇴직금, 성과급, 연차수당, 4대 보험",
        "salary": "연봉 3,600 만원 (주 40시간)",
        "location": "서울 중구 청파로 450, 3층 (중림동,신흥빌딩)",
        "employee": "7명",
        "link": "http://www.dwni.co.kr",
        "revenue": "8억 6,137만원"
      },
      {
        "companyName": "(주)청우정보기술",
        "establish": "2015-06-26",
        "logo": "https://imgs.jobkorea.co.kr/img1/_whitebg/200X80/Co_Logo/Logo/2015/12/2k7ao00aRm_jKwigfvtz3k2vm0goYeIp_gnic2om.jpg?v=202408020312&hash=r&serviceCode=CL",
        "pic1": "https://www.theteams.kr/image?width=750&image=https://www.theteams.kr/includes/uploads/recruit/%EC%A3%BC%EC%8B%9D%ED%9A%8C%EC%82%AC_%EC%B2%AD%EC%9A%B0%EC%A0%95%EB%B3%B4%EA%B8%B0%EC%88%A0_20210308.png",
        "pic2": "",
        "pic3": "",
        "pic4": "",
        "pic5": "",
        "body": "(주)청우정보기술은 컴퓨터 및 주변기기 도소매, 소프트웨어 패키지 공급, 소프트웨어 개발 및 공급, 컴퓨터 및 사무기기 유지보수를 전문으로 하는 중소기업입니다. 지속적인 성장과 함께 다양한 고객들에게 우수한 서비스를 제공하고 있습니다.",
        "track": "시스템 소프트웨어 개발",
        "stack": "SE, 정보통신, H/W",
        "welfare": "우수사원포상, 퇴직금, 성과급, 야근수당, 휴일(특근)수당, 자격증수당, 4대 보험, 자격증취득지원, 교육비 지원, 간식 제공, 음료제공(차, 커피), 공기청정기, 회식강요 안함, 자유복장, 칼퇴근 보장, 주 52시간제 준수, 주 40시간제 시행, 연차,",
        "salary": "협의 후 결정",
        "location": "세종 조치원읍 돌마루4길 6, 307호 (서창리,성현빌)",
        "employee": "16명",
        "link": "https://www.saramin.co.kr/zf_user/company-info/view?csn=L0g3SmZxUGlPQlRwUi9kT3RtYjlsZz09&popup_yn=y",
        "revenue": "12억 7,610만원"
      },
      {
        "companyName": "링크정보통신(주)",
        "establish": "1998-03-06",
        "logo": "https://pds.saramin.co.kr/company/logo/202209/01/rhinx1_6lhr-1ppw9le_logo.PNG",
        "pic1": "https://pds.saramin.co.kr/workenv-bg/202209/05/rhq3qt_bppg-1ppw9le_workenv-bg.jpg",
        "pic2": "https://pds.saramin.co.kr/workenv-bg/202209/01/rhims3_nplc-1ppw9le_workenv-bg.jpg",
        "pic3": "",
        "pic4": "",
        "pic5": "",
        "body": "링크정보통신(주)은 1998년 창사 이래 다수의 SI/NI 사업 수행과 IT 시장의 우수한 국내·외 제조사와의 파트너 관계를 통해 정보보안 전문기업으로 성장하였습니다. 네트워크 및 시스템 인프라에서 차세대 정보보안 분야까지 다양한 솔루션과 전문적인 기술력을 기반으로 200여개 이상의 공공/민수/금융 분야의 다양한 고객에게 인정을 받고 있으며, 차별화된 서비스와 기술지원을 통해 고객 만족을 넘어서 고객 감동의 가치를 실현하고 있습니다. 변화하는 시대에 맞춰 고객의 다양한 정보보호요구를 만족시키기 위해 지속적으로 노력하고 있습니다.",
        "track": "네트워크",
        "stack": "정보보호, 정보통신",
        "welfare": "우수사원포상, 퇴직금, 성과급, 야근수당, 휴일(특근)수당, 자격증수당, 4대 보험, 자격증취득지원, 교육비 지원, 간식 제공, 음료제공(차, 커피), 공기청정기, 회식강요 안함, 자유복장, 칼퇴근 보장, 주 52시간제 준수, 주 40시간제 시행, 연차, 여름휴가, 경조휴가제, 근로자의 날 휴무, 휴양시설 제공",
        "salary": "면접 후 결정",
        "location": "서울 구로구 디지털로30길 28, 1005호 (구로동,마리오타워)",
        "employee": "36명",
        "link": "http://www.linkic.co.kr",
        "revenue": "157억 4,176만원"
      },
      {
        "companyName": "(주)솔리드이엔지",
        "establish": "2003-07-23",
        "logo": "https://pds.saramin.co.kr/company/logo/201902/26/pnj34j_v3wn-0_logo.jpg",
        "pic1": "https://pds.saramin.co.kr/workenv-bg/202402/21/s970th_d2e3-1mq6nrw_workenv-bg.png",
        "pic2": "https://pds.saramin.co.kr/workenv-bg/202402/21/s970uq_fzol-1mq6nrw_workenv-bg.png",
        "pic3": "",
        "pic4": "",
        "pic5": "",
        "body": "(주)솔리드이엔지는 3D PLM, HPC, CLOUD를 기반으로 한 Total ICT 분야의 제품 및 컨설팅 서비스 선도기업으로, AI를 활용하여 전 분야의 혁신을 추구하고 있습니다. 본사는 대전에 위치하며, 서울 및 영남 지사를 기반으로 600여개 고객사에 제품 및 서비스를 제공하고 있습니다. 안정된 기반 매출에 더해 혁신적 AI, CLOUD 신사업이 더해지며 선도적 IT 기업으로 발전하고 있습니다.",
        "track": "시스템 소프트웨어 개발",
        "stack": "정보통신, JAVA, AWS",
        "welfare": "우수사원포상, 퇴직금, 4대 보험, 자격증취득지원, 교육비 지원, 건강검진, 각종 경조사 지원",
        "salary": "협의 후 결정",
        "location": "대전 유성구 반석동로40번길 40",
        "employee": "67명",
        "link": "http://www.solideng.co.kr",
        "revenue": "258억 3,704만원"
      },
      {
        "companyName": "(주)지엠코퍼레이션",
        "establish": "2021-08-13",
        "logo": "https://modo-phinf.pstatic.net/20210629_280/1624967132360Ueeav_PNG/mosa831H6H.png?type=round256_256",
        "pic1": "https://image.ec21.com/company/g/gm/gmk/gmkcorp/img/kml_home.gif",
        "pic2": "https://cdn.kr.aving.net/news/photo/201112/223752_384040_1548.jpg",
        "pic3": "",
        "pic4": "",
        "pic5": "",
        "body": "(주)지엠코퍼레이션은 응용 소프트웨어 개발 및 공급업체로, 세종시 공공 프로젝트를 위해 웹개발 경력 직원을 모집합니다. 본사는 경기도 안양시에 위치하며, 다양한 혜택과 함께 지원 가능합니다.",
        "track": "백엔드",
        "stack": "JAVA, JSP, MYSQL",
        "welfare": "",
        "salary": "면접 후 결정",
        "location": "경기 안양시 동안구 관악대로434번길 9-12, 2층 209호 (관양동, 라츠빌)",
        "employee": "7명",
        "link": "https://gmcorporation.modoo.at/",
        "revenue": "8억 4,537만원"
      },
      {
        "companyName": "(주)플랜아이",
        "establish": "2004-11-26",
        "logo": "https://pds.saramin.co.kr/company/logo/201902/27/pnk3zm_c3iv-0_logo.jpg",
        "pic1": "https://pds.saramin.co.kr/workenv-bg/202109/06/qyzwqu_yu7y-1p4snuq_workenv-bg.jpg",
        "pic2": "https://pds.saramin.co.kr/workenv-bg/202109/06/qyzwqv_2gb9-1p4snuq_workenv-bg.JPG",
        "pic3": "",
        "pic4": "",
        "pic5": "",
        "body": "(주)플랜아이는 응용 소프트웨어 개발 및 공급업체로, 지식 서비스 데이터 이관을 위한 Java 개발자를 모집합니다. 본사는 대전 유성구에 위치하며, 다양한 혜택과 함께 지원 가능합니다.",
        "track": "백엔드",
        "stack": "JAVA, 데이터마이닝",
        "welfare": "넓은 회사로비, 계열사 존재",
        "salary": "협의 후 결정",
        "location": "대전 유성구 문지로 282-10",
        "employee": "121명",
        "link": "http://www.plani.co.kr",
        "revenue": "평균연봉 4,288만원"
      },
      {
        "companyName": "(주)바이브컴퍼니",
        "establish": "2000-07-08",
        "logo": "https://pds.saramin.co.kr/company/logo/202010/25/qir72j_35ds-ay5bn3_logo.png",
        "pic1": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/%EB%B0%94%EC%9D%B4%EB%B8%8C%EC%BB%B4%ED%8D%BC%EB%8B%88_%EC%82%AC%EC%98%A5.jpg/445px-%EB%B0%94%EC%9D%B4%EB%B8%8C%EC%BB%B4%ED%8D%BC%EB%8B%88_%EC%82%AC%EC%98%A5.jpg",
        "pic2": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvO6urDCCAtc_DLwjww-zl8_itWgdZDTbhbQ&s",
        "pic3": "",
        "pic4": "",
        "pic5": "",
        "body": "(주)바이브컴퍼니는 국내 최고의 포털기업인 다음커뮤니케이션의 중장기 전략의 일환으로 설립된 회사로, 자연어 처리와 인공지능, 지식기술 및 최첨단 IT 기술을 활용하여 CRM 및 기타 솔루션 분야에서 최고의 성능과 이식성을 갖춘 제품을 만들고 있습니다.",
        "track": "시스템 소프트웨어 개발",
        "stack": "JAVA, 빅데이터, DBMS",
        "welfare": "좋은 코드리뷰 문화",
        "salary": "면접 후 결정",
        "location": "서울 용산구 독서당로 97",
        "employee": "211명",
        "link": "http://www.vaiv.kr",
        "revenue": "평균 연봉 4,660만원"
      },
      {
        "companyName": "(주)오토노머스에이투지",
        "establish": "2018-03-12",
        "logo": "https://pds.saramin.co.kr/company/logo/202204/08/ra05in_elcj-1kkp35q_logo.png",
        "pic1": "https://pds.saramin.co.kr/workenv-bg/202204/08/ra06hw_6wcy-1kkp35q_workenv-bg.jpg",
        "pic2": "https://pds.saramin.co.kr/workenv-bg/202204/08/ra06hx_yf16-1kkp35q_workenv-bg.jpg",
        "pic3": "https://pds.saramin.co.kr/workenv-bg/202204/08/ra07f8_8ycy-1kkp35q_workenv-bg.jpg",
        "pic4": "",
        "pic5": "",
        "body": "(주)오토노머스에이투지는 자율주행 솔루션 전문 기업으로, 독보적인 기술력과 혁신적인 솔루션을 바탕으로 자율주행 분야에서 선도적인 위치를 차지하고 있습니다. 2023년 시리즈B 투자 340억 유치를 성공적으로 완료하였으며, '가이드하우스 인사이트' 발표에 따르면 글로벌 자율주행 기술종합순위 세계 13위에 올랐습니다. 2024년 중소벤처기업부로부터 '예비유니콘'으로 선정되며 글로벌 초일류 자율주행 솔루션 기업으로 도약하고 있습니다.",
        "track": "자율주행",
        "stack": "Unity, 자율주행, 정보통신",
        "welfare": "건강검진, 각종 경조사 지원, 단체 상해보험, 퇴직연금, 우수사원포상, 성과급, 4대 보험, 워크샵, 자기계발비 지원, 점심식사 제공, 사내동호회 운영, 간식 제공, 음료제공(차, 커피), 휴게실, 회의실, 공기청정기, 노트북, 사무용품 지급, 안마실/안마의자, 회식강요 안함, 자유복장, 자유로운 연차사용",
        "salary": "면접 후 결정",
        "location": "경북 경산시 가마실길 50, 201호",
        "employee": "152명",
        "link": "http://www.autoa2z.co.kr",
        "revenue": "비공개"
      },
      {
        "companyName": "(주)에이치지",
        "establish": "2014-03-12",
        "logo": "http://www.hgworks.co.kr/images/logo/newhglogo.png",
        "pic1": "http://www.hgworks.co.kr/images/background/company.jpeg",
        "pic2": "",
        "pic3": "",
        "pic4": "",
        "pic5": "",
        "body": "(주)에이치지는 SI/SM 및 JAVA 웹프로그래밍 분야에서 전문성을 가지고 있는 기업입니다. 신입 웹프로그래머를 대상으로 다양한 프로젝트와 경험을 쌓을 수 있는 기회를 제공합니다. 세종특별자치시에서 근무하며, 정규직 및 계약직으로 근무할 수 있는 기회를 제공합니다.",
        "track": "백엔드",
        "stack": "JAVA, 서버개발, 클라우드",
        "welfare": "4대보험, 자유로운연차",
        "salary": "협의 후 결정",
        "location": "",
        "employee": "20명",
        "link": "http://www.hgworks.co.kr/",
        "revenue": ""
      },
      {
        "companyName": "㈜에세텔",
        "establish": "2001-04-25",
        "logo": "https://pds.saramin.co.kr/company/logo/201902/27/pnknp6_u747-0_logo.jpg",
        "pic1": "https://www.essetel.com/source/img/sub1_01_img01.jpg",
        "pic2": "",
        "pic3": "",
        "pic4": "",
        "pic5": "",
        "body": "㈜에세텔은 정보통신장비, 버스 및 차량정보안내장치, 구내방송장치, 다중화장치, 데이터포트장치, 열차행선안내장치, 무선통신장치, 유무선원격제어장치, 전화교환기네트워크연 등 다양한 정보통신 솔루션을 제공하는 전문기업입니다. SW개발 팀장급 정규직을 대상으로 다양한 프로젝트와 경험을 쌓을 수 있는 기회를 제공합니다.",
        "track": "프론트엔드",
        "stack": "JAVA, C++, JavaScript",
        "welfare": "4대보험, 각종 경조사 지원, 다양한 급여제도, 포상제도, 생일선물, 교육 지원제도",
        "salary": "면접 후 결정",
        "location": "대전 유성구 유성대로1205번길 10",
        "employee": "43명",
        "link": "http://www.essetel.com",
        "revenue": "87억 4,448만원"
      },
      {
        "companyName": "㈜아츠코리아",
        "establish": "2010-08-23",
        "logo": "https://pds.saramin.co.kr/company/logo/201902/27/pnkbp6_j7w0-0_logo.jpg",
        "pic1": "https://static.wanted.co.kr/images/company/370/ai0qcau78zvxzee5__1080_790.jpg",
        "pic2": "",
        "pic3": "",
        "pic4": "",
        "pic5": "",
        "body": "㈜아츠코리아는 근로자파견, 업무제공용역, 인재추천컨설팅을 제공하는 상용 인력 공급 및 인사관리 서비스업 전문 기업입니다. 오프라인 중심의 헤드헌팅서비스를 제공하며, 구직자와 구인기업이 모두 만족하는 Position을 추천하고 있습니다. 직원의 복리후생에도 중점을 두고 있습니다.",
        "track": "시스템 소프트웨어 개발",
        "stack": "C++, RTOS, C언어",
        "welfare": "퇴직금, 4대 보험, 연차",
        "salary": "면접 후 결정",
        "location": "서울 강남구 테헤란로 313, 1511호",
        "employee": "",
        "link": "http://www.ahrz.co.kr",
        "revenue": ""
      },
      {
        "companyName": "㈜맨파워코리아",
        "establish": "2001-04-25",
        "logo": "https://pds.saramin.co.kr/company/logo/202306/02/rvlsjc_3hqt-1a0yb3h_logo.png",
        "pic1": "https://pds.saramin.co.kr/workenv-bg/202407/19/sguiqo_162l-1a0yb38_workenv-bg.png",
        "pic2": "https://pds.saramin.co.kr/workenv-bg/202306/02/rvltzv_nfdr-1a0yb3h_workenv-bg.png",
        "pic3": "https://pds.saramin.co.kr/workenv-bg/202406/12/seyavk_hhjo-1a0yb3h_workenv-bg.png",
        "pic4": "",
        "pic5": "",
        "body": "㈜맨파워코리아는 국내 반도체 제조 기업으로, Windows Application 개발 경력자를 모집합니다. 다양한 혜택과 함께 지원 가능합니다.",
        "track": "시스템 소프트웨어 개발",
        "stack": "C++, C#, Windows",
        "welfare": "4대보험, 퇴직금, 연차",
        "salary": "협의 후 결정",
        "location": "",
        "employee": "5,404명",
        "link": "https://www.manpowergroup.com",
        "revenue": "3,358억 9,825만원"
      },
      {
        "companyName": "마스코리아(주)",
        "establish": "2018-07-20",
        "logo": "https://pds.saramin.co.kr/company/logo/201904/10/ppqim2_1wrn-1p6cgrt_logo.jpg",
        "pic1": "https://pds.saramin.co.kr/workenv-bg/202103/12/qpueep_edbw-xrt686_workenv-bg.JPG",
        "pic2": "https://pds.saramin.co.kr/workenv-bg/202103/12/qpueeq_30zn-xrt686_workenv-bg.JPG",
        "pic3": "",
        "pic4": "",
        "pic5": "",
        "body": "마스코리아(주)는 자율주행 인프라 및 스마트 도로 전광 표지 (VMS) 서비스 전문 기업으로, 인공 지능 영상 기반 도로 살얼음 및 안개 검지 장치를 독자 개발하여 판매 중입니다. 회사는 급성장 중이며 능력 있는 직원을 추가 채용하고 있습니다.",
        "track": "자율주행",
        "stack": "임베디드, 펌웨어",
        "welfare": "퇴직연금, 스톡옵션, 퇴직금, 성과급, 4대 보험, 신규 입사자 교육(OJT), 직무능력향상교육, 점심식사 제공, 식비 지원, 휴게실, 회의실, 카페테리아, 사내 정원, 노트북, 사무용품 지급, 수평적 조직문화, 자유로운 연차사용, 칼퇴근 보장",
        "salary": "면접 후 결정",
        "location": "세종특별자치시 집현중앙7로 3, 602호",
        "employee": "50명",
        "link": "http://www.maaskr.com",
        "revenue": "80억원"
    }
];

async function realCompany() {
    try {
      // 데이터베이스 연결 확인
      await sequelize.authenticate();
  
      // 자격증 데이터 삽입
      await Company.bulkCreate(companies, { ignoreDuplicates: true });
      console.log('회사정보가 성공적으로 삽입되었습니다.');
  
      console.log('데이터베이스 시딩이 완료되었습니다.');
    } catch (error) {
      console.error('데이터베이스 시딩 중 오류 발생:', error);
    } finally {
      // 데이터베이스 연결 종료
      await sequelize.close();
      console.log('데이터베이스 연결이 종료되었습니다.');
    }
  }
  
  // 시딩 함수 실행
  realCompany();