const { sequelize } = require('./config/db');
const QualificationInfo = require('./models/ITInfo/QualificationInfo/qualificationInfoModel');

const qualifications = [
  {
      "title": "정보처리기사 3회 필기",
      "startdate": "2024-06-18",
      "enddate": "2024-06-21",
      "exam_startdate": "2024-07-05",
      "exam_enddate": "2024-07-27",
      "resultdate": "2024-08-07",
      "logo": "https://www.sh-news.com/imgdata/sh-news_com/202006/2020062937455075.png",
      "pic1": null,
      "pic2": null,
      "pic3": null,
      "pic4": null,
      "pic5": null,
      "body": "① 시 행 처 : 한국산업인력공단\n② 관련학과 : 모든 학과 응시가능 \n③ 시험과목\n- 필기 1. 소프트웨어설계 2. 소프트웨어개발 3. 데이터베이스구축 4. 프로그래밍언어활용 5. 정보시스템구축관리\n- 실기 : 정보처리 실무\n④ 검정방법\n- 필기 : 객관식 4지 택일형, 과목당 20문항(과목당 30분)\n- 실기 : 필답형(2시간30분)",
      "pass_standard": "합격기준\n- 필기 : 100점을 만점으로 하여 과목당 40점 이상, 전과목 평균 60점 이상.",
      "workview": "",
      "qualification": "4년제: 졸업 또는 4학년1학기 이상 재학/휴학/제적\n3년제: 졸업 후 1년 실무 경력\n2년제: 졸업 후 2년 실무 경력\n동일 직무 분야에서 4년 이상 실무경력\n기능사 취득후 3년 실무경력\n산업기사 취득 후 1년 실무경력",
      "testinfo": "",
      "problems": null,
      "qualification_name": "정보처리기사 필기",
      "relate_department": "과학기술정보통신부",
      "agency": "한국산업인력공단",
      "link": "https://www.q-net.or.kr/man001.do?imYn=Y&gSite=Q",
      "fee": 19400
  },
  {
      "title": "정보처리기사 3회 실기",
      "startdate": "2024-09-10",
      "enddate": "2024-09-13",
      "exam_startdate": "2024-10-19",
      "exam_enddate": "2024-11-08",
      "resultdate": "2024-12-11",
      "logo": "https://www.sh-news.com/imgdata/sh-news_com/202006/2020062937455075.png",
      "pic1": null,
      "pic2": null,
      "pic3": null,
      "pic4": null,
      "pic5": null,
      "body": "① 시 행 처 : 한국산업인력공단\n② 관련학과 : 모든 학과 응시가능 \n③ 시험과목\n- 필기 1. 소프트웨어설계 2. 소프트웨어개발 3. 데이터베이스구축 4. 프로그래밍언어활용 5. 정보시스템구축관리\n- 실기 : 정보처리 실무\n④ 검정방법\n- 필기 : 객관식 4지 택일형, 과목당 20문항(과목당 30분)\n- 실기 : 필답형(2시간30분)",
      "pass_standard": "- 실기 : 100점을 만점으로 하여 60점 이상.",
      "workview": "",
      "qualification": "4년제: 졸업 또는 4학년1학기 이상 재학/휴학/제적\n3년제: 졸업 후 1년 실무 경력\n2년제: 졸업 후 2년 실무 경력\n동일 직무 분야에서 4년 이상 실무경력\n기능사 취득후 3년 실무경력\n산업기사 취득 후 1년 실무경력",
      "testinfo": "",
      "problems": null,
      "qualification_name": "정보처리기사 실기",
      "relate_department": "과학기술정보통신부",
      "agency": "한국산업인력공단",
      "link": "https://www.q-net.or.kr/man001.do?imYn=Y&gSite=Q",
      "fee": 22600
  },
  {
      "title": "정보보안기사 3회 필기",
      "startdate": "2024-09-09",
      "enddate": "2024-09-12",
      "exam_startdate": "2024-09-23",
      "exam_enddate": "2024-10-20",
      "resultdate": "2024-10-25",
      "logo": "https://www.kca.kr/home/www/images/524161008242.jpg",
      "pic1": null,
      "pic2": null,
      "pic3": null,
      "pic4": null,
      "pic5": null,
      "body": "정보보호에 대한 지식과 운용 경험을 바탕으로 실무적인 시스템과 서버, 네트워크 장비 및 보안시스템 운용을 통해, 보안업무 및 보안정책수립과 보안대책 구현, 정보보안 관련 법규 준수 여부를 판단하는 등의 업무 수행",
      "pass_standard": "과목당 100점을 만점으로하여 매과목 40점 이상, 전과목평균 60점이상\n:과목당 20문항",
      "workview": "",
      "qualification": "「국가기술자격법 시행령」 제12조의2(국가기술자격의 등급과 응시자격)\n정보보안기사의 응시자격은「국가기술자격법 시행규칙」 제10조의2(응시자격)별표 11의 2에 근거하여 모든 직무분야에서 응시가능",
      "testinfo": "",
      "problems": null,
      "qualification_name": "정보보안기사 필기",
      "relate_department": "한국방송통신전파진흥원",
      "agency": "KCA",
      "link": "https://www.cq.or.kr/qh_quagm01_020.do",
      "fee": 18800
  },
  {
      "title": "정보보안기사 3회 실기",
      "startdate": "2024-10-28",
      "enddate": "2024-10-31",
      "exam_startdate": "2024-11-23",
      "exam_enddate": "2024-12-08",
      "resultdate": "2024-12-24",
      "logo": "https://www.kca.kr/home/www/images/524161008242.jpg",
      "pic1": null,
      "pic2": null,
      "pic3": null,
      "pic4": null,
      "pic5": null,
      "body": "정보보호에 대한 지식과 운용 경험을 바탕으로 실무적인 시스템과 서버, 네트워크 장비 및 보안시스템 운용을 통해, 보안업무 및 보안정책수립과 보안대책 구현, 정보보안 관련 법규 준수 여부를 판단하는 등의 업무 수행",
      "pass_standard": "100점을 만점으로 60점 이상",
      "workview": "",
      "qualification": "「국가기술자격법 시행령」 제12조의2(국가기술자격의 등급과 응시자격)\n정보보안기사의 응시자격은「국가기술자격법 시행규칙」 제10조의2(응시자격)별표 11의 2에 근거하여 모든 직무분야에서 응시가능",
      "testinfo": "",
      "problems": null,
      "qualification_name": "정보보안기사 실기",
      "relate_department": "한국방송통신전파진흥원",
      "agency": "KCA",
      "link": "https://www.cq.or.kr/qh_quagm01_020.do",
      "fee": 21900
  },
  {
      "title": "제 54회 SQLD",
      "startdate": "2024-07-22",
      "enddate": "2024-07-26",
      "exam_startdate": "2024-08-24",
      "exam_enddate": "2024-08-24",
      "resultdate": "2024-09-20",
      "logo": "https://www.kdata.or.kr/_img/kdata_og.jpg",
      "pic1": null,
      "pic2": null,
      "pic3": null,
      "pic4": null,
      "pic5": null,
      "body": "SQL 개발자(SQLD*, SQL Developer)란 데이터베이스와 데이터 모델링에 대한 지식을 바탕으로 응용 소프트웨어를 개발하면서 데이터를 조작하고 추출하는데 있어서 정확하고 최적의 성능을 발휘하는 SQL을 작성할 수 있는 개발자를 말한다.\nSQL 개발자 자격시험의 과목은 총 2과목으로 구성되어 있으며 데이터 모델링의 이해 과목을 바탕으로 SQL 기본 및 활용을 수행하는 능력을 검정한다.",
      "pass_standard": "합격기준: 총점 60점 이상\n과락기준: 과목별 40% 미만 취득",
      "workview": "",
      "qualification": "제한 없음",
      "testinfo": "",
      "problems": null,
      "qualification_name": "SQL 개발자",
      "relate_department": "한국데이터산업진흥원",
      "agency": "Kdata",
      "link": "https://www.dataq.or.kr/www/main.do",
      "fee": 50000
  },
  {
      "title": "제 51회 SQLP",
      "startdate": "2024-07-22",
      "enddate": "2024-07-26",
      "exam_startdate": "2024-08-24",
      "exam_enddate": "2024-08-24",
      "resultdate": "2024-09-20",
      "logo": "https://www.kdata.or.kr/_img/kdata_og.jpg",
      "pic1": null,
      "pic2": null,
      "pic3": null,
      "pic4": null,
      "pic5": null,
      "body": "SQL 전문가(SQLP*, SQL Professional)란 데이터베이스와 데이터모델링에 대한 지식을 바탕으로 데이터를 조작하고 추출하는데 있어서 정확하고 최적의 성능을 발휘하는 SQL을 작성할 수 있고, 이를 토대로 SQL을 내포하는 데이터베이스 프로그램이나 응용 소프트웨어의 성능을 최적화하거나, 이러한 성능 최적화를 지원할 수 있는 데이터베이스 개체(뷰, 인덱스 등)의 설계와 구현 등의 직무를 수행하는 전문가를 말한다.\nSQL 전문가 자격시험의 과목은 총 3과목으로 구성되어 있으며 데이터 모델링의 이해 과목을 바탕으로 SQL 기본 및 활용, SQL 고급활용 및 튜닝을 수행하는 능력을 검정한다.",
      "pass_standard": "합격기준: 총점 100점 기준 75점 이상 취득\n과락기준: 과목별 40% 미만 취득",
      "workview": "",
      "qualification": "SQL 전문가 자격시험의 응시자격은 아래와 같으며 응시자격은 시험일 기준 시험일 이전에 응시자격 요건이 충족되어야 한다. 학력/경력기준 또는 자격기준 중 한가지의 요건이 충족될 경우 응시자격이 부여된다.\n학사학위 이상 취득한 자\n전문학사학위 취득 후 실무경력 2년 이상인 자\n고등학교 졸업한 후 실무경력 4년 이상인 자\n국내외 데이터베이스 관련 자격을 취득한 자\n** IBM, Microsoft, Oracle, Sybase에서 인증하는 데이터베이스 관련 자격\nSQL 개발자 자격을 취득한 자\n데이터아키텍처 전문가 및 준전문가 자격을 취득한 자",
      "testinfo": "",
      "problems": null,
      "qualification_name": "SQL 전문가",
      "relate_department": "한국데이터산업진흥원",
      "agency": "Kdata",
      "link": "https://www.dataq.or.kr/www/main.do",
      "fee": 100000
  },
  {
      "title": "리눅스마스터 2급 1차",
      "startdate": "2024-07-29",
      "enddate": "2024-08-07",
      "exam_startdate": "2024-07-30",
      "exam_enddate": "2024-08-08",
      "resultdate": "2024-08-08",
      "logo": "https://pbs.twimg.com/profile_images/3436807073/6241dee425bfe548c8be5782d6429f76_400x400.jpeg",
      "pic1": null,
      "pic2": null,
      "pic3": null,
      "pic4": null,
      "pic5": null,
      "body": "리눅스로 운영되는 전세계 80%이상의 스마트폰, 70%이상의 클라우드 서버, 세계 상위의 500대 슈퍼컴퓨터를 비롯해서 5세대 이동통신(5G), 사물인터넷(IoT), 드론, 자율주행차 등 미래성장동력 분야에서 다양한 응용기반기술에 토대가 되는 자격종목\n리눅스 기반 시스템의 관리능력을 평가하는 1급 자격과 리눅스 운영시스템의 프로그램 사용능력을 평가하는 2급 자격으로 구분\n리눅스마스터 1, 2급은 NCS(국가직무능력표준) 등을 바탕으로 SW기술자의 체계적 역량 가이드라인 ITSQF(IT분야역량체계)의 IT시스템관리자(L5, L3)로 인정",
      "pass_standard": "1차 60점 이상,\n2차 60점 이상(과목당 40% 미만 과락)",
      "workview": "",
      "qualification": "1차 : 제한없음\n2차 : 1차 시험 합격자에 한해 성적공개일 기준으로 2년이내 응시",
      "testinfo": "시험출제 리눅스버전 안내\nㆍ필기 : 커널 4.x이상\n※ 레드햇 계열 : RHEL/Rocky Linux 8, 데비안 계열: ubuntu 18.04 이상\nㆍ실기 : Rocky Linux 8.9 (VirtualBox를 활용하여 리눅스 구동)",
      "problems": null,
      "qualification_name": "리눅스마스터 2급",
      "relate_department": "한국정보통신진흥협회",
      "agency": "KAIT 정보통신기술자격검정",
      "link": "https://www.kiat.or.kr/front/user/main.do",
      "fee": 22000
  },
  {
      "title": "리눅스마스터 2급 2차",
      "startdate": "2024-07-30",
      "enddate": "2024-08-09",
      "exam_startdate": "2024-09-07",
      "exam_enddate": "2024-09-07",
      "resultdate": "2024-10-04",
      "logo": "https://pbs.twimg.com/profile_images/3436807073/6241dee425bfe548c8be5782d6429f76_400x400.jpeg",
      "pic1": null,
      "pic2": null,
      "pic3": null,
      "pic4": null,
      "pic5": null,
      "body": "리눅스로 운영되는 전세계 80%이상의 스마트폰, 70%이상의 클라우드 서버, 세계 상위의 500대 슈퍼컴퓨터를 비롯해서 5세대 이동통신(5G), 사물인터넷(IoT), 드론, 자율주행차 등 미래성장동력 분야에서 다양한 응용기반기술에 토대가 되는 자격종목\n리눅스 기반 시스템의 관리능력을 평가하는 1급 자격과 리눅스 운영시스템의 프로그램 사용능력을 평가하는 2급 자격으로 구분\n리눅스마스터 1, 2급은 NCS(국가직무능력표준) 등을 바탕으로 SW기술자의 체계적 역량 가이드라인 ITSQF(IT분야역량체계)의 IT시스템관리자(L5, L3)로 인정",
      "pass_standard": "1차 60점 이상,\n2차 60점 이상(과목당 40% 미만 과락)",
      "workview": "",
      "qualification": "1차 : 제한없음\n2차 : 1차 시험 합격자에 한해 성적공개일 기준으로 2년이내 응시",
      "testinfo": "시험출제 리눅스버전 안내\nㆍ필기 : 커널 4.x이상\n※ 레드햇 계열 : RHEL/Rocky Linux 8, 데비안 계열: ubuntu 18.04 이상\nㆍ실기 : Rocky Linux 8.9 (VirtualBox를 활용하여 리눅스 구동)",
      "problems": null,
      "qualification_name": "리눅스마스터 2급",
      "relate_department": "한국정보통신진흥협회",
      "agency": "KAIT 정보통신기술자격검정",
      "link": "https://www.kiat.or.kr/front/user/main.do",
      "fee": 44000
  },
  {
      "title": "리눅스마스터 1급 1차",
      "startdate": "2024-07-29",
      "enddate": "2024-08-09",
      "exam_startdate": "2024-09-07",
      "exam_enddate": "2024-09-07",
      "resultdate": "2024-10-04",
      "logo": "https://pbs.twimg.com/profile_images/3436807073/6241dee425bfe548c8be5782d6429f76_400x400.jpeg",
      "pic1": null,
      "pic2": null,
      "pic3": null,
      "pic4": null,
      "pic5": null,
      "body": "리눅스로 운영되는 전세계 80%이상의 스마트폰, 70%이상의 클라우드 서버, 세계 상위의 500대 슈퍼컴퓨터를 비롯해서 5세대 이동통신(5G), 사물인터넷(IoT), 드론, 자율주행차 등 미래성장동력 분야에서 다양한 응용기반기술에 토대가 되는 자격종목\n리눅스 기반 시스템의 관리능력을 평가하는 1급 자격과 리눅스 운영시스템의 프로그램 사용능력을 평가하는 2급 자격으로 구분\n리눅스마스터 1, 2급은 NCS(국가직무능력표준) 등을 바탕으로 SW기술자의 체계적 역량 가이드라인 ITSQF(IT분야역량체계)의 IT시스템관리자(L5, L3)로 인정",
      "pass_standard": "1차 60점 이상(과목당 40% 미만 과락),\n2차 60점 이상",
      "workview": "",
      "qualification": "1차 : 제한없음\n2차 : 1차 시험 합격자에 한해 성적공개일 기준으로 2년이내 응시",
      "testinfo": "시험출제 리눅스버전 안내\nㆍ필기 : 커널 4.x이상\n※ 레드햇 계열 : RHEL/Rocky Linux 8, 데비안 계열: ubuntu 18.04 이상\nㆍ실기 : Rocky Linux 8.9 (VirtualBox를 활용하여 리눅스 구동)",
      "problems": null,
      "qualification_name": "리눅스마스터 1급",
      "relate_department": "한국정보통신진흥협회",
      "agency": "KAIT 정보통신기술자격검정",
      "link": "https://www.kiat.or.kr/front/user/main.do",
      "fee": 55000
  },
  {
      "title": "리눅스마스터 1급 2차",
      "startdate": "2024-10-07",
      "enddate": "2024-10-18",
      "exam_startdate": "2024-11-09",
      "exam_enddate": "2024-11-09",
      "resultdate": "2024-11-29",
      "logo": "https://pbs.twimg.com/profile_images/3436807073/6241dee425bfe548c8be5782d6429f76_400x400.jpeg",
      "pic1": null,
      "pic2": null,
      "pic3": null,
      "pic4": null,
      "pic5": null,
      "body": "리눅스로 운영되는 전세계 80%이상의 스마트폰, 70%이상의 클라우드 서버, 세계 상위의 500대 슈퍼컴퓨터를 비롯해서 5세대 이동통신(5G), 사물인터넷(IoT), 드론, 자율주행차 등 미래성장동력 분야에서 다양한 응용기반기술에 토대가 되는 자격종목\n리눅스 기반 시스템의 관리능력을 평가하는 1급 자격과 리눅스 운영시스템의 프로그램 사용능력을 평가하는 2급 자격으로 구분\n리눅스마스터 1, 2급은 NCS(국가직무능력표준) 등을 바탕으로 SW기술자의 체계적 역량 가이드라인 ITSQF(IT분야역량체계)의 IT시스템관리자(L5, L3)로 인정",
      "pass_standard": "1차 60점 이상(과목당 40% 미만 과락),\n2차 60점 이상",
      "workview": "",
      "qualification": "1차 : 제한없음\n2차 : 1차 시험 합격자에 한해 성적공개일 기준으로 2년이내 응시",
      "testinfo": "시험출제 리눅스버전 안내\nㆍ필기 : 커널 4.x이상\n※ 레드햇 계열 : RHEL/Rocky Linux 8, 데비안 계열: ubuntu 18.04 이상\nㆍ실기 : Rocky Linux 8.9 (VirtualBox를 활용하여 리눅스 구동)",
      "problems": null,
      "qualification_name": "리눅스마스터 1급",
      "relate_department": "한국정보통신진흥협회",
      "agency": "KAIT 정보통신기술자격검정",
      "link": "https://www.kiat.or.kr/front/user/main.do",
      "fee": 77000
  },
  {
      "title": "컴퓨터활용능력 1급 필기",
      "startdate": "2024-01-01",
      "enddate": "2024-01-01",
      "exam_startdate": "2024-01-01",
      "exam_enddate": "2024-01-01",
      "resultdate": "2024-01-01",
      "logo": "https://yt3.googleusercontent.com/BWD8CrBKs2SlqU78JuVE0Awlc9BxQcU9qlghYOJ_sVMEDAz9tIT-h9fWvQN4H_cbcZR7QtQbxq8=s900-c-k-c0x00ffffff-no-rj",
      "pic1": null,
      "pic2": null,
      "pic3": null,
      "pic4": null,
      "pic5": null,
      "body": "산업계의 정보화가 진전되면서 영업, 재무, 생산 등의 분야에 대한 경영분석은 물론 데이터 관리가 필수적입니다.\n<컴퓨터활용능력> 검정은 사무자동화의 필수 프로그램인 스프레드시트(SpreadSheet), 데이터베이스(Database) 활용능력을 평가하는 국가기술자격 시험입니다.\n2024년부터 컴퓨터활용능력 출제기준이 변경됩니다. 자세한 출제기준 변경 내용은 하단 2024년 적용 출제기준 파일을 참고하시기 바랍니다.",
      "pass_standard": "필기 : 매과목 100점 만점에 과목당 40점 이상이고 평균 60점 이상\n실기 : 100점 만점에 70점 이상(1급은 두과목 모두 70점 이상)",
      "workview": "공무원 채용 가산점\n- 소방공무원(사무관리직) : 컴퓨터활용능력1급(3%), 컴퓨터활용능력2급(1%)\n- 경찰공무원 : 컴퓨터활용능력1, 2급(2점 가점)\n학점은행제 학점인정 : 1급 14학점, 2급 6학점\n300여개 공공기관·공기업 등 채용·승진 우대",
      "qualification": "",
      "testinfo": "상시시험",
      "problems": null,
      "qualification_name": "컴퓨터활용능력 1급",
      "relate_department": "대한상공회의소",
      "agency": "대한상공회의소",
      "link": "https://license.korcham.net/indexmain.jsp",
      "fee": 20500
  },
  {
      "title": "컴퓨터활용능력 1급 실기",
      "startdate": "2024-01-01",
      "enddate": "2024-01-01",
      "exam_startdate": "2024-01-01",
      "exam_enddate": "2024-01-01",
      "resultdate": "2024-01-01",
      "logo": "https://yt3.googleusercontent.com/BWD8CrBKs2SlqU78JuVE0Awlc9BxQcU9qlghYOJ_sVMEDAz9tIT-h9fWvQN4H_cbcZR7QtQbxq8=s900-c-k-c0x00ffffff-no-rj",
      "pic1": null,
      "pic2": null,
      "pic3": null,
      "pic4": null,
      "pic5": null,
      "body": "산업계의 정보화가 진전되면서 영업, 재무, 생산 등의 분야에 대한 경영분석은 물론 데이터 관리가 필수적입니다.\n<컴퓨터활용능력> 검정은 사무자동화의 필수 프로그램인 스프레드시트(SpreadSheet), 데이터베이스(Database) 활용능력을 평가하는 국가기술자격 시험입니다.\n2024년부터 컴퓨터활용능력 출제기준이 변경됩니다. 자세한 출제기준 변경 내용은 하단 2024년 적용 출제기준 파일을 참고하시기 바랍니다.",
      "pass_standard": "필기 : 매과목 100점 만점에 과목당 40점 이상이고 평균 60점 이상\n실기 : 100점 만점에 70점 이상(1급은 두과목 모두 70점 이상)",
      "workview": "공무원 채용 가산점\n- 소방공무원(사무관리직) : 컴퓨터활용능력1급(3%), 컴퓨터활용능력2급(1%)\n- 경찰공무원 : 컴퓨터활용능력1, 2급(2점 가점)\n학점은행제 학점인정 : 1급 14학점, 2급 6학점\n300여개 공공기관·공기업 등 채용·승진 우대",
      "qualification": "",
      "testinfo": "상시시험",
      "problems": null,
      "qualification_name": "컴퓨터활용능력 1급",
      "relate_department": "대한상공회의소",
      "agency": "대한상공회의소",
      "link": "https://license.korcham.net/indexmain.jsp",
      "fee": 25000
  },
  {
      "title": "컴퓨터활용능력 2급 필기",
      "startdate": "2024-01-01",
      "enddate": "2024-01-01",
      "exam_startdate": "2024-01-01",
      "exam_enddate": "2024-01-01",
      "resultdate": "2024-01-01",
      "logo": "https://yt3.googleusercontent.com/BWD8CrBKs2SlqU78JuVE0Awlc9BxQcU9qlghYOJ_sVMEDAz9tIT-h9fWvQN4H_cbcZR7QtQbxq8=s900-c-k-c0x00ffffff-no-rj",
      "pic1": null,
      "pic2": null,
      "pic3": null,
      "pic4": null,
      "pic5": null,
      "body": "산업계의 정보화가 진전되면서 영업, 재무, 생산 등의 분야에 대한 경영분석은 물론 데이터 관리가 필수적입니다.\n<컴퓨터활용능력> 검정은 사무자동화의 필수 프로그램인 스프레드시트(SpreadSheet), 데이터베이스(Database) 활용능력을 평가하는 국가기술자격 시험입니다.\n2024년부터 컴퓨터활용능력 출제기준이 변경됩니다. 자세한 출제기준 변경 내용은 하단 2024년 적용 출제기준 파일을 참고하시기 바랍니다.",
      "pass_standard": "필기 : 매과목 100점 만점에 과목당 40점 이상이고 평균 60점 이상\n실기 : 100점 만점에 70점 이상(1급은 두과목 모두 70점 이상)",
      "workview": "공무원 채용 가산점\n- 소방공무원(사무관리직) : 컴퓨터활용능력1급(3%), 컴퓨터활용능력2급(1%)\n- 경찰공무원 : 컴퓨터활용능력1, 2급(2점 가점)\n학점은행제 학점인정 : 1급 14학점, 2급 6학점\n300여개 공공기관·공기업 등 채용·승진 우대",
      "qualification": "",
      "testinfo": "상시시험",
      "problems": null,
      "qualification_name": "컴퓨터활용능력 2급",
      "relate_department": "대한상공회의소",
      "agency": "대한상공회의소",
      "link": "https://license.korcham.net/indexmain.jsp",
      "fee": 20500
  },
  {
      "title": "컴퓨터활용능력 2급 실기",
      "startdate": "2024-01-01",
      "enddate": "2024-01-01",
      "exam_startdate": "2024-01-01",
      "exam_enddate": "2024-01-01",
      "resultdate": "2024-01-01",
      "logo": "https://yt3.googleusercontent.com/BWD8CrBKs2SlqU78JuVE0Awlc9BxQcU9qlghYOJ_sVMEDAz9tIT-h9fWvQN4H_cbcZR7QtQbxq8=s900-c-k-c0x00ffffff-no-rj",
      "pic1": null,
      "pic2": null,
      "pic3": null,
      "pic4": null,
      "pic5": null,
      "body": "산업계의 정보화가 진전되면서 영업, 재무, 생산 등의 분야에 대한 경영분석은 물론 데이터 관리가 필수적입니다.\n<컴퓨터활용능력> 검정은 사무자동화의 필수 프로그램인 스프레드시트(SpreadSheet), 데이터베이스(Database) 활용능력을 평가하는 국가기술자격 시험입니다.\n2024년부터 컴퓨터활용능력 출제기준이 변경됩니다. 자세한 출제기준 변경 내용은 하단 2024년 적용 출제기준 파일을 참고하시기 바랍니다.",
      "pass_standard": "필기 : 매과목 100점 만점에 과목당 40점 이상이고 평균 60점 이상\n실기 : 100점 만점에 70점 이상(1급은 두과목 모두 70점 이상)",
      "workview": "공무원 채용 가산점\n- 소방공무원(사무관리직) : 컴퓨터활용능력1급(3%), 컴퓨터활용능력2급(1%)\n- 경찰공무원 : 컴퓨터활용능력1, 2급(2점 가점)\n학점은행제 학점인정 : 1급 14학점, 2급 6학점\n300여개 공공기관·공기업 등 채용·승진 우대",
      "qualification": "",
      "testinfo": "상시시험",
      "problems": null,
      "qualification_name": "컴퓨터활용능력 2급",
      "relate_department": "대한상공회의소",
      "agency": "대한상공회의소",
      "link": "https://license.korcham.net/indexmain.jsp",
      "fee": 25000
  },
  {
      "title": "빅데이터분석기사 필기",
      "startdate": "2024-08-05",
      "enddate": "2024-08-09",
      "exam_startdate": "2024-09-07",
      "exam_enddate": "2024-09-07",
      "resultdate": "2024-09-27",
      "logo": "https://www.kdata.or.kr/_img/kdata_og.jpg",
      "pic1": null,
      "pic2": null,
      "pic3": null,
      "pic4": null,
      "pic5": null,
      "body": "관련 근거\n국가기술자격법 및 동법 시행령\n빅데이터분석기사 정의\n빅데이터 이해를 기반으로 빅데이터 분석 기획, 빅데이터 수집·저장·처리, 빅데이터 분석 및 시각화를 수행하는 실무자를 말한다.\n빅데이터분석기사의 필요성\n전 세계적으로 빅데이터가 미래성장동력으로 인식돼, 각국 정부에서는 관련 기업투자를 끌어내는 등 국가·기업의 주요 전략분야로 부상하고 있다.\n국가와 기업의 경쟁력 확보를 위해 빅데이터 분석 전문가의 수요는 증가하고 있으나, 수요 대비 공급 부족으로 인력 확보에 어려움이 높은 실정이다.\n이에 정부차원에서 빅데이터 분석 전문가 양성과 함께 체계적으로 역량을 검증할 수 있는 국가기술자격 수요가 높은 편이다.\n빅데이터분석기사의 직무\n대용량의 데이터 집합으로부터 유용한 정보를 찾고 결과를 예측하기 위해 목적에 따라 분석기술과 방법론을 기반으로 정형/비정형 대용량 데이터를 구축, 탐색, 분석하고 시각화를 수행하는 업무를 수행한다.",
      "pass_standard": "과목당 100점을 만점으로\n1. 전 과목 40점 이상\n2. 전 과목 평균 60점 이상",
      "workview": "",
      "qualification": "다음 중 하나에 해당하는 사람\n1. 대학졸업자등 또는 졸업예정자 (전공 무관)\n2. 3년제 전문대학 졸업자등으로서 졸업 후 1년 이상 직장경력이 있는 사람 (전공, 직무분야 무관)\n3. 2년제 전문대학 졸업자등으로서 졸업 후 2년 이상 직장경력이 있는 사람 (전공, 직무분야 무관)\n4. 기사 등급 이상의 자격을 취득한 사람 (종목 무관)\n5. 기사 수준 기술훈련과정 이수자 또는 그 이수예정자 (종목 무관)\n6. 산업기사 등급 이상의 자격을 취득한 후 1년 이상 직장경력이 있는 사람 (종목, 직무분야 무관)\n7. 산업기사 수준 기술훈련과정 이수자로서 이수 후 2년 이상 직장경력이 있는 사람 (종목, 직무분야 무관)\n8. 기능사 등급 이상의 자격을 취득한 후 3년 이상 직장경력이 있는 사람 (종목, 직무분야 무관)\n9. 4년 이상 직장경력이 있는 사람 (직무분야 무관)\n※ 졸업증명서 및 경력증명서 제출 필요",
      "testinfo": "",
      "problems": null,
      "qualification_name": "빅데이터분석기사",
      "relate_department": "한국데이터산업진흥원",
      "agency": "Kdata",
      "link": "https://www.dataq.or.kr/www/main.do",
      "fee": 17800
  },
  {
      "title": "빅데이터분석기사 실기",
      "startdate": "2024-10-28",
      "enddate": "2024-11-01",
      "exam_startdate": "2024-11-30",
      "exam_enddate": "2024-11-30",
      "resultdate": "2024-12-20",
      "logo": "https://www.kdata.or.kr/_img/kdata_og.jpg",
      "pic1": null,
      "pic2": null,
      "pic3": null,
      "pic4": null,
      "pic5": null,
      "body": "관련 근거\n국가기술자격법 및 동법 시행령\n빅데이터분석기사 정의\n빅데이터 이해를 기반으로 빅데이터 분석 기획, 빅데이터 수집·저장·처리, 빅데이터 분석 및 시각화를 수행하는 실무자를 말한다.\n빅데이터분석기사의 필요성\n전 세계적으로 빅데이터가 미래성장동력으로 인식돼, 각국 정부에서는 관련 기업투자를 끌어내는 등 국가·기업의 주요 전략분야로 부상하고 있다.\n국가와 기업의 경쟁력 확보를 위해 빅데이터 분석 전문가의 수요는 증가하고 있으나, 수요 대비 공급 부족으로 인력 확보에 어려움이 높은 실정이다.\n이에 정부차원에서 빅데이터 분석 전문가 양성과 함께 체계적으로 역량을 검증할 수 있는 국가기술자격 수요가 높은 편이다.\n빅데이터분석기사의 직무\n대용량의 데이터 집합으로부터 유용한 정보를 찾고 결과를 예측하기 위해 목적에 따라 분석기술과 방법론을 기반으로 정형/비정형 대용량 데이터를 구축, 탐색, 분석하고 시각화를 수행하는 업무를 수행한다.",
      "pass_standard": "100점을 만점으로 60점이상",
      "workview": "",
      "qualification": "다음 중 하나에 해당하는 사람\n1. 대학졸업자등 또는 졸업예정자 (전공 무관)\n2. 3년제 전문대학 졸업자등으로서 졸업 후 1년 이상 직장경력이 있는 사람 (전공, 직무분야 무관)\n3. 2년제 전문대학 졸업자등으로서 졸업 후 2년 이상 직장경력이 있는 사람 (전공, 직무분야 무관)\n4. 기사 등급 이상의 자격을 취득한 사람 (종목 무관)\n5. 기사 수준 기술훈련과정 이수자 또는 그 이수예정자 (종목 무관)\n6. 산업기사 등급 이상의 자격을 취득한 후 1년 이상 직장경력이 있는 사람 (종목, 직무분야 무관)\n7. 산업기사 수준 기술훈련과정 이수자로서 이수 후 2년 이상 직장경력이 있는 사람 (종목, 직무분야 무관)\n8. 기능사 등급 이상의 자격을 취득한 후 3년 이상 직장경력이 있는 사람 (종목, 직무분야 무관)\n9. 4년 이상 직장경력이 있는 사람 (직무분야 무관)\n※ 졸업증명서 및 경력증명서 제출 필요",
      "testinfo": "",
      "problems": null,
      "qualification_name": "빅데이터분석기사",
      "relate_department": "한국데이터산업진흥원",
      "agency": "Kdata",
      "link": "https://www.dataq.or.kr/www/main.do",
      "fee": 40800
  },
  {
      "title": "ADSP",
      "startdate": "2024-09-30",
      "enddate": "2024-10-04",
      "exam_startdate": "2024-11-03",
      "exam_enddate": "2024-11-03",
      "resultdate": "2024-11-29",
      "logo": "https://www.kdata.or.kr/_img/kdata_og.jpg",
      "pic1": null,
      "pic2": null,
      "pic3": null,
      "pic4": null,
      "pic5": null,
      "body": "데이터분석 준전문가 정의\n데이터분석 준전문가(ADsP : Advanced Data Analytics Semi-Professional)란 데이터 이해에 대한 기본지식을 바탕으로 데이터분석 기획 및 데이터분석 등의 직무를 수행하는 실무자를 말한다.\n데이터분석 자격검정의 필요성\n오늘날 데이터 처리 및 분석을 통한 데이터 활용은 생산성 향상, 고부가가치 및 고용 창출 등 국가 경제적 가치 창출의 핵심동력으로 급부상하고 있다.\n특히, 과학적 의사 결정의 토대가 되는 데이터분석은 기업과 국가의 생산성 향상에 기여하는 혁신 도구로 각광을 받고 있다. 기업체들은 자사의 경영 전략에 데이터분석을 도입하여 수익 증대를 실현할 수 있으며, 데이터분석을 공공영역에 도입할 경우에는 높은 사회적‧경제적 효과가 발생할 것으로 예상된다. 이러한 데이터분석의 가능성을 실현하기 위해서는 데이터의 다각적 분석을 통해 조직의 전략방향을 제시하는 우수한 역량을 갖춘 데이터분석 준전문가의 확보가 필수적이다.\n미국과 유럽을 비롯한 세계 각국은 데이터분석 시장 선점을 위해 데이터분석 준전문가 확보와 양성에 집중하고 있는 실정이다. 반면, 국내 상황은 데이터 전문가 인력양성 체계 미흡 등으로 데이터 관련 신규 비즈니스의 고부가가치 창출 등 연계 효과 저하가 우려되며, 사회 전반의 데이터 활용에 필수적인 데이터분석 능력을 객관적으로 검증, 공공․민간 분야의 실무형 데이터분석 준전문가 양성이 필요한 시점이다.\n이에 한국데이터산업진흥원은 전문인력의 실질적 수요자인 사업주를 대변하여 데이터분석 준전문가 자격검정을 실시하고자 한다. 이를 통해 산업 현장에 부응하는 민간자격을 부여하고, 자격취득자에게 직무 수행에 대한 자신감 고취와 함께 보다 나은 직무 수행 기회 제공 및 사회적 지위의 향상은 물론 기업의 국제 경쟁력 제고에도 기여할 것이다.",
      "pass_standard": "합격기준: 총점 60점 이상\n과락기준: 과목별 40% 미만 취득",
      "workview": "",
      "qualification": "제한 없음",
      "testinfo": "",
      "problems": null,
      "qualification_name": "데이터분석 준전문가",
      "relate_department": "한국데이터산업진흥원",
      "agency": "Kdata",
      "link": "https://www.dataq.or.kr/www/main.do",
      "fee": 50000
  },
  {
      "title": "ADP 필기",
      "startdate": "2024-07-01",
      "enddate": "2024-07-05",
      "exam_startdate": "2024-08-10",
      "exam_enddate": "2024-08-10",
      "resultdate": "2024-11-06",
      "logo": "https://www.kdata.or.kr/_img/kdata_og.jpg",
      "pic1": null,
      "pic2": null,
      "pic3": null,
      "pic4": null,
      "pic5": null,
      "body": "데이터분석 전문가 정의\n데이터분석 전문가란 데이터 이해 및 처리 기술에 대한 기본지식을 바탕으로 데이터분석 기획, 데이터분석, 데이터 시각화 업무를 수행하고 이를 통해 프로세스 혁신 및 마케팅 전략 결정 등의 과학적 의사결정을 지원하는 직무를 수행하는 전문가를 말한다.\n데이터분석 자격검정의 필요성\n오늘날 데이터 처리 및 분석을 통한 데이터 활용은 생산성 향상, 고부가가치 및 고용 창출 등 국가 경제적 가치 창출의 핵심동력으로 급부상하고 있다.\n특히, 과학적 의사 결정의 토대가 되는 데이터분석은 기업과 국가의 생산성 향상에 기여하는 혁신 도구로 각광을 받고 있다. 기업체들은 자사의 경영 전략에 데이터분석을 도입하여 수익 증대를 실현할 수 있으며, 데이터분석을 공공영역에 도입할 경우에는 높은 사회적‧경제적 효과가 발생할 것으로 예상된다. 이러한 데이터분석의 가능성을 실현하기 위해서는 데이터의 다각적 분석을 통해 조직의 전략방향을 제시하는 우수한 역량을 갖춘 데이터분석 전문가의 확보가 필수적이다.\n미국과 유럽을 비롯한 세계 각국은 데이터분석 시장 선점을 위해 데이터분석 전문가 확보와 양성에 집중하고 있는 실정이다. 반면, 국내 상황은 데이터 전문가 인력양성 체계 미흡 등으로 데이터 관련 신규 비즈니스의 고부가가치 창출 등 연계 효과 저하가 우려되며, 사회 전반의 데이터 활용에 필수적인 데이터분석 능력을 객관적으로 검증, 공공․민간 분야의 실무형 데이터분석 전문가 양성이 필요한 시점이다.\n이에 한국데이터산업진흥원은 전문인력의 실질적 수요자인 사업주를 대변하여 데이터분석 전문가 자격검정을 실시하고자 한다. 이를 통해 산업 현장에 부응하는 민간자격을 부여하고, 자격취득자에게 직무 수행에 대한 자신감 고취와 함께 보다 나은 직무 수행 기회 제공 및 사회적 지위의 향상은 물론 기업의 국제 경쟁력 제고에도 기여할 것이다.",
      "pass_standard": "합격기준: 총점 70점 이상\n과락기준: 과목별 40% 미만 취득",
      "workview": "",
      "qualification": "데이터분석 전문가 자격검정 시험의 응시자격은 아래와 같으며 응시자격은 필기시험일 기준 시험일 이전에 응시자격 요건이 충족되어야 한다. 경력/학력기준 또는 자격보유기준 중 한가지의 요건이 충족될 경우 응시자격이 부여된다\n박사학위를 취득한자\n석사학위를 취득하고 해당 분야의 실무경력 1년 이상인자\n학사학위를 취득하고 해당 분야의 실무경력 3년 이상인자\n전문대학 졸업후 해당 분야의 실무경력 6년 이상인자\n고등학교 졸업후 해당 분야의 실무경력 9년 이상인자\n데이터분석 준전문가 자격을 취득한 자",
      "testinfo": "필기시험 합격자 발표일로부터 2년의 유효기간을 가지며, 2년 이내에 접수 가능한 실기검정에 응시 가능\n(다만, 필기시험 합격일로부터 2년간 검정이 2회 미만으로 시행된 경우 그 다음에 이어지는 해당 필기시험 1회를 면제한다.)\n※ 검정의 시행은 자격검정 시행기관의 시행여부로 수험자의 응시횟수와는 무관",
      "problems": null,
      "qualification_name": "데이터분석 전문가",
      "relate_department": "한국데이터산업진흥원",
      "agency": "Kdata",
      "link": "https://www.dataq.or.kr/www/main.do",
      "fee": 80000
  },
  {
      "title": "ADP 실기",
      "startdate": "2024-09-09",
      "enddate": "2024-09-13",
      "exam_startdate": "2024-10-12",
      "exam_enddate": "2024-10-12",
      "resultdate": "2024-11-08",
      "logo": "https://www.kdata.or.kr/_img/kdata_og.jpg",
      "pic1": null,
      "pic2": null,
      "pic3": null,
      "pic4": null,
      "pic5": null,
      "body": "데이터분석 전문가 정의\n데이터분석 전문가란 데이터 이해 및 처리 기술에 대한 기본지식을 바탕으로 데이터분석 기획, 데이터분석, 데이터 시각화 업무를 수행하고 이를 통해 프로세스 혁신 및 마케팅 전략 결정 등의 과학적 의사결정을 지원하는 직무를 수행하는 전문가를 말한다.\n데이터분석 자격검정의 필요성\n오늘날 데이터 처리 및 분석을 통한 데이터 활용은 생산성 향상, 고부가가치 및 고용 창출 등 국가 경제적 가치 창출의 핵심동력으로 급부상하고 있다.\n특히, 과학적 의사 결정의 토대가 되는 데이터분석은 기업과 국가의 생산성 향상에 기여하는 혁신 도구로 각광을 받고 있다. 기업체들은 자사의 경영 전략에 데이터분석을 도입하여 수익 증대를 실현할 수 있으며, 데이터분석을 공공영역에 도입할 경우에는 높은 사회적‧경제적 효과가 발생할 것으로 예상된다. 이러한 데이터분석의 가능성을 실현하기 위해서는 데이터의 다각적 분석을 통해 조직의 전략방향을 제시하는 우수한 역량을 갖춘 데이터분석 전문가의 확보가 필수적이다.\n미국과 유럽을 비롯한 세계 각국은 데이터분석 시장 선점을 위해 데이터분석 전문가 확보와 양성에 집중하고 있는 실정이다. 반면, 국내 상황은 데이터 전문가 인력양성 체계 미흡 등으로 데이터 관련 신규 비즈니스의 고부가가치 창출 등 연계 효과 저하가 우려되며, 사회 전반의 데이터 활용에 필수적인 데이터분석 능력을 객관적으로 검증, 공공․민간 분야의 실무형 데이터분석 전문가 양성이 필요한 시점이다.\n이에 한국데이터산업진흥원은 전문인력의 실질적 수요자인 사업주를 대변하여 데이터분석 전문가 자격검정을 실시하고자 한다. 이를 통해 산업 현장에 부응하는 민간자격을 부여하고, 자격취득자에게 직무 수행에 대한 자신감 고취와 함께 보다 나은 직무 수행 기회 제공 및 사회적 지위의 향상은 물론 기업의 국제 경쟁력 제고에도 기여할 것이다.",
      "pass_standard": "실기 총점 100점 기준 75점 이상",
      "workview": "",
      "qualification": "데이터분석 전문가 자격검정 시험의 응시자격은 아래와 같으며 응시자격은 필기시험일 기준 시험일 이전에 응시자격 요건이 충족되어야 한다. 경력/학력기준 또는 자격보유기준 중 한가지의 요건이 충족될 경우 응시자격이 부여된다\n박사학위를 취득한자\n석사학위를 취득하고 해당 분야의 실무경력 1년 이상인자\n학사학위를 취득하고 해당 분야의 실무경력 3년 이상인자\n전문대학 졸업후 해당 분야의 실무경력 6년 이상인자\n고등학교 졸업후 해당 분야의 실무경력 9년 이상인자\n데이터분석 준전문가 자격을 취득한 자",
      "testinfo": "필기시험 합격자 발표일로부터 2년의 유효기간을 가지며, 2년 이내에 접수 가능한 실기검정에 응시 가능\n(다만, 필기시험 합격일로부터 2년간 검정이 2회 미만으로 시행된 경우 그 다음에 이어지는 해당 필기시험 1회를 면제한다.)\n※ 검정의 시행은 자격검정 시행기관의 시행여부로 수험자의 응시횟수와는 무관",
      "problems": null,
      "qualification_name": "데이터분석 전문가",
      "relate_department": "한국데이터산업진흥원",
      "agency": "Kdata",
      "link": "https://www.dataq.or.kr/www/main.do",
      "fee": 70000
  },
  {
      "title": "DAsP",
      "startdate": "2024-08-26",
      "enddate": "2024-08-30",
      "exam_startdate": "2024-09-28",
      "exam_enddate": "2024-09-28",
      "resultdate": "2024-10-25",
      "logo": "https://www.kdata.or.kr/_img/kdata_og.jpg",
      "pic1": null,
      "pic2": null,
      "pic3": null,
      "pic4": null,
      "pic5": null,
      "body": "데이터아키텍처 직무 정의\n데이터아키텍처(DA, Data Architecture) 직무는 기업의 모든 업무를 데이터 측면에서 처음부터 끝까지 체계화하는 것으로 정의된다.\n데이터아키텍처 준전문가 정의\n데이터아키텍처 준전문가(DAsP, Data Architecture Semi-Professional)란 효과적인 데이터아키텍처 구축을 위해 데이터 요건 분석, 데이터 표준화, 데이터 모델링, 데이터베이스 설계와 이용 등의 직무를 수행하는 실무자를 말한다.",
      "pass_standard": "합격기준: 총점 60점 이상\n과락기준: 과목별 40% 미만 취득",
      "workview": "최근 기업의 정보화 전략을 둘러싼 화두는 단연 전사아키텍처(EA, Enterprise Architecture)이다. 이를 대변하듯 국내 대기업 CIO의 IT전략에 전사아키텍처가 빠짐없이 등장하고 있다. 특히 전사아키텍처의 구성요소 중 데이터아키텍처(DA, Data Architecture)가 가장 중요하게 인식되고 있다. 그 이유는 데이터아키텍처가 정보시스템을 구성하는 기본 요소인 데이터에 연관된 모든 계층을 총망라한 체계적인 방법이기 때문이다. 다시 말해, 정보시스템의 근간을 체계화하는 것이 데이터아키텍처이다. 그러나 이러한 데이터아키텍처의 중요성에 비해 이에 대한 전문적 지식을 갖춘 인재는 상대적으로 매우 빈약한 것이 현실이다.\n이에 한국데이터산업진흥원은 전문인력의 실질적 수요자인 사업주를 대변하여 데이터아키텍처 준전문가 자격검정을 실시하고자 한다. 이를 통해 사업현장에 부응하는 자격을 부여하고, 자격 취득자에게 직업 기회 제공 및 사회적 지위(취업, 승진, 보수 등)의 향상은 물론 기업의 국제경쟁력 제고에도 기여할 것이다.",
      "qualification": "제한 없음",
      "testinfo": "데이터아키텍처 준전문가 자격시험의 과목은 크게 기본 과목과 전공 과목으로 구성되며, 기본 과목에 대해서는 각 과목의 전반적인 이해를 평가하고 전공과목은 각 과목의 심화 능력 평가한다. 검정과목별 주요 내용은 아래와 같다\n데이터아키텍처 준전문가 자격시험의 과목은 총 4과목으로 구성되어 있으며 전사아키텍처 이해 과목을 바탕으로 데이터 요건 분석, 데이터 표준화, 데이터 모델링을 수행하는 능력을 검정한다.",
      "problems": null,
      "qualification_name": "데이터아키텍처 준전문가",
      "relate_department": "한국데이터산업진흥원",
      "agency": "Kdata",
      "link": "https://www.dataq.or.kr/www/main.do",
      "fee": 50000
  },
  {
      "title": "DAP",
      "startdate": "2024-08-26",
      "enddate": "2024-08-30",
      "exam_startdate": "2024-09-28",
      "exam_enddate": "2024-09-28",
      "resultdate": "2024-10-25",
      "logo": "https://www.kdata.or.kr/_img/kdata_og.jpg",
      "pic1": null,
      "pic2": null,
      "pic3": null,
      "pic4": null,
      "pic5": null,
      "body": "데이터아키텍처 정의\n데이터아키텍처(DA, Data Architecture)란 기업의 모든 업무를 데이터 측면에서 처음부터 끝까지 체계화하는 것이다.\n데이터아키텍처 전문가 정의\n데이터아키텍처 전문가(DAP, Data Architecture Professional)란 효과적인 데이터아키텍처 구축을 위해 전사아키텍처와 데이터품질관리에 대한 지식을 바탕으로 데이터 요건분석, 데이터 표준화, 데이터 모델링, 데이터베이스 설계와 이용 등의 직무를 수행하는 실무자를 말한다.",
      "pass_standard": "합격기준: 총점 75점 이상\n과락기준: 과목별 40% 미만 취득",
      "workview": "최근 기업의 정보화 전략을 둘러싼 화두는 단연 전사아키텍처(EA, Enterprise Architecture)이다. 이를 대변하듯 국내 대기업 CIO의 IT전략에 전사아키텍처가 빠짐없이 등장하고 있다. 특히 전사아키텍처의 구성요소 중 데이터아키텍처(DA, Data Architecture)가 가장 중요하게 인식되고 있다. 그 이유는 데이터아키텍처가 정보시스템을 구성하는 기본 요소인 데이터에 연관된 모든 계층을 총망라한 체계적인 방법이기 때문이다. 다시 말해, 정보시스템의 근간을 체계화하는 것이 데이터아키텍처이다. 그러나 이러한 데이터아키텍처의 중요성에 비해 이에 대한 전문적 지식을 갖춘 인재는 상대적으로 매우 빈약한 현실이다.\n이에 한국데이터산업진흥원은 전문인력의 실질적 수요자인 사업주를 대변하여 데이터아키텍처 전문가 자격검정제도를 실시하고자 한다. 이를 통해 사업현장에 부응하는 민간자격을 부여하고, 자격 취득자에게 직업 기회 제공 및 사회적 지위(취업, 승진, 보수 등)의 향상은 물론 기업의 국제 경쟁력 제고에도 기여할 것이다.",
      "qualification": "박사학위 취득한 자\n석사학위 취득한 후 정보처리분야의 실무경력 1년 이상인 자\n학사학위 취득한 후 정보처리분야의 실무경력 3년 이상인 자\n전문대학 졸업한 후 정보처리분야의 실무경력 6년 이상인 자\n고등학교 졸업한 후 정보처리분야의 실무경력 9년 이상인 자\n국가기술자격 중 기술사 자격을 취득한 자\n국가기술자격 중 기사 자격을 취득한 후 정보처리분야의 실무경력 1년 이상인 자\n국가기술자격 중 산업기사 자격을 취득한 후 정보처리분야의 실무경력 4년 이상인 자\n학사학위 취득자 중 데이터베이스관련 자격을 취득한 자\n** IBM, Microsoft, Oracle, Sybase에서 인증하는 데이터베이스 관련 자격\n데이터아키텍처 준전문가 자격을 취득한 자\nSQL 전문가 또는 SQL 개발자 자격을 취득한 자",
      "testinfo": "데이터아키텍처 전문가 자격시험의 과목은 총 6과목으로 구성되어 있으며 전사아키텍처 이해를 바탕으로 데이터 요건 분석, 데이터 표준화, 데이터 모델링, 데이터베이스 설계와 이용, 데이터 품질 관리를 수행하는 능력을 검정한다.\n데이터아키텍처 전문가 자격시험의 과목은 총 6과목으로 구성되며, 필기 100문제와 논리데이터모델 및 표준화정의서를 작성하는 실기 1문제로 구성되어 있습니다. 검정과목별 출제 문항 및 배점은 아래와 같다.",
      "problems": null,
      "qualification_name": "데이터아키텍처 전문가",
      "relate_department": "한국데이터산업진흥원",
      "agency": "Kdata",
      "link": "https://www.dataq.or.kr/www/main.do",
      "fee": 100000
  },
  {
      "title": "네트워크관리사 1급 필기",
      "startdate": "2024-09-24",
      "enddate": "2024-09-27",
      "exam_startdate": "2024-10-27",
      "exam_enddate": "2024-10-27",
      "resultdate": "2024-10-29",
      "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTunDCYKBDPeLgcMAm6LtwPLyniARh9mcXztQ&s",
      "pic1": null,
      "pic2": null,
      "pic3": null,
      "pic4": null,
      "pic5": null,
      "body": "네트워크 관리에 관한 전문지식을 토대로 네트워크 보안기술, Design, Traffic 분산기술 등 네트워크 전문기술자로서 필요한 IT 기술 및 네트워크 실무. 관리 능력 검정",
      "pass_standard": "60점 이상",
      "workview": "네트워크관리사란 서버를 구축하고 보안 설정, 시스템 최적화 등 네트워크구축 및 이를 효과적으로 관리할 수 있는 인터넷 관련 기술력에 대한 자격이다.",
      "qualification": "당협회 시행 해당종목 2급자격 소지자\n전기,전자,통신,정보처리 직무분야 국가기술 자격취득자 중 아래 해당자\n가. 기술사, 기사, 산업기사 자격증 소지자\n나. 기능사 자격 취득한 후 동일직무 분야에서 2년이상 실무에 종사한 자\nIT관련 사업장에서 5년이상 종사한자",
      "testinfo": "필기: 검정문제의 문항수는 각 과목별로 5~18문항씩 출제되며, 1급은 60분, 2급은 50분의 제한시간을 둔다.\n실기: 1 SET(1~20문항)가 출제되며 제한시간 내에 지시된 사항을 수행해야 한다.",
      "problems": null,
      "qualification_name": "네트워크관리사 1급",
      "relate_department": "한국정보통신자격협회",
      "agency": "ICQA",
      "link": "https://www.icqa.or.kr/cn/",
      "fee": 43000
  },
  {
      "title": "네트워크관리사 1급 실기",
      "startdate": "2024-10-29",
      "enddate": "2024-11-01",
      "exam_startdate": "2024-12-08",
      "exam_enddate": "2024-12-08",
      "resultdate": "2024-12-17",
      "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTunDCYKBDPeLgcMAm6LtwPLyniARh9mcXztQ&s",
      "pic1": null,
      "pic2": null,
      "pic3": null,
      "pic4": null,
      "pic5": null,
      "body": "네트워크 관리에 관한 전문지식을 토대로 네트워크 보안기술, Design, Traffic 분산기술 등 네트워크 전문기술자로서 필요한 IT 기술 및 네트워크 실무. 관리 능력 검정",
      "pass_standard": "60점 이상",
      "workview": "네트워크관리사란 서버를 구축하고 보안 설정, 시스템 최적화 등 네트워크구축 및 이를 효과적으로 관리할 수 있는 인터넷 관련 기술력에 대한 자격이다.",
      "qualification": "해당등급 필기 합격자로서 합격일로부터 2년 이내의 응시자",
      "testinfo": "필기: 검정문제의 문항수는 각 과목별로 5~18문항씩 출제되며, 1급은 60분, 2급은 50분의 제한시간을 둔다.\n실기: 1 SET(1~21문항)가 출제되며 제한시간 내에 지시된 사항을 수행해야 한다.",
      "problems": null,
      "qualification_name": "네트워크관리사 1급",
      "relate_department": "한국정보통신자격협회",
      "agency": "ICQA",
      "link": "https://www.icqa.or.kr/cn/",
      "fee": 100000
  },
  {
      "title": "네트워크관리사 2급 필기",
      "startdate": "2024-10-08",
      "enddate": "2024-10-11",
      "exam_startdate": "2024-11-03",
      "exam_enddate": "2024-11-03",
      "resultdate": "2024-11-05",
      "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTunDCYKBDPeLgcMAm6LtwPLyniARh9mcXztQ&s",
      "pic1": null,
      "pic2": null,
      "pic3": null,
      "pic4": null,
      "pic5": null,
      "body": "네트워크 관련 업무 수행을 위한 일반적인 운용지식과 구축기술, NOS운영, Packet분석, Monitoring, 인터넷기술, Protocol 등 기초 이론과 실무능력 검정",
      "pass_standard": "60점 이상",
      "workview": "네트워크관리사란 서버를 구축하고 보안 설정, 시스템 최적화 등 네트워크구축 및 이를 효과적으로 관리할 수 있는 인터넷 관련 기술력에 대한 자격이다.",
      "qualification": "제한없음 (연령,나이..)",
      "testinfo": "필기: 검정문제의 문항수는 각 과목별로 5~18문항씩 출제되며, 1급은 60분, 2급은 50분의 제한시간을 둔다.\n실기: 1 SET(1~22문항)가 출제되며 제한시간 내에 지시된 사항을 수행해야 한다.",
      "problems": null,
      "qualification_name": "네트워크관리사 2급",
      "relate_department": "한국정보통신자격협회",
      "agency": "ICQA",
      "link": "https://www.icqa.or.kr/cn/",
      "fee": 43000
  },
  {
      "title": "네트워크관리사 2급 실기",
      "startdate": "2024-11-05",
      "enddate": "2024-11-08",
      "exam_startdate": "2024-12-01",
      "exam_enddate": "2024-12-01",
      "resultdate": "2024-12-10",
      "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTunDCYKBDPeLgcMAm6LtwPLyniARh9mcXztQ&s",
      "pic1": null,
      "pic2": null,
      "pic3": null,
      "pic4": null,
      "pic5": null,
      "body": "네트워크 관련 업무 수행을 위한 일반적인 운용지식과 구축기술, NOS운영, Packet분석, Monitoring, 인터넷기술, Protocol 등 기초 이론과 실무능력 검정",
      "pass_standard": "60점 이상",
      "workview": "네트워크관리사란 서버를 구축하고 보안 설정, 시스템 최적화 등 네트워크구축 및 이를 효과적으로 관리할 수 있는 인터넷 관련 기술력에 대한 자격이다.",
      "qualification": "해당등급 필기 합격자로서 합격일로부터 2년 이내의 응시자",
      "testinfo": "필기: 검정문제의 문항수는 각 과목별로 5~18문항씩 출제되며, 1급은 60분, 2급은 50분의 제한시간을 둔다.\n실기: 1 SET(1~23문항)가 출제되며 제한시간 내에 지시된 사항을 수행해야 한다.",
      "problems": null,
      "qualification_name": "네트워크관리사 2급",
      "relate_department": "한국정보통신자격협회",
      "agency": "ICQA",
      "link": "https://www.icqa.or.kr/cn/",
      "fee": 78000
  }
];


async function seedQualification() {
    try {
      // 데이터베이스 연결 확인
      await sequelize.authenticate();
  
      // 자격증 데이터 삽입
      await QualificationInfo.bulkCreate(qualifications, { ignoreDuplicates: true });
      console.log('자격증이 성공적으로 삽입되었습니다.');
  
      console.log('데이터베이스 시딩이 완료되었습니다.');
    } catch (error) {
      console.error('데이터베이스 시딩 중 오류 발생:', error);
    } finally {
      // 데이터베이스 연결 종료
      await sequelize.close();
      console.log('데이터베이스 연결이 종료되었습니다.');
    }
  }
  
  // 시딩 함수 실행
  seedQualification();